#!/usr/bin/env python3
"""
KarpTube scraper — wide-net Palantir media feed.
Pulls everything Palantir-related from news, RSS, YouTube, Reddit,
social, podcasts, newsletters, blogs. 7-day rolling window.
Writes to palantir-dashboard/karptube.js
"""
import hashlib
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD_DIR = os.path.join(ROOT, "palantir-dashboard")
OUTPUT_PATH = os.path.join(DASHBOARD_DIR, "karptube.js")
SEEN_PATH = os.path.join(os.path.dirname(__file__), "karptube_seen_ids.json")

sys.path.insert(0, os.path.dirname(__file__))
import source_registry


def load_seen():
    if os.path.exists(SEEN_PATH):
        with open(SEEN_PATH) as f:
            return set(json.load(f))
    return set()


def save_seen(seen):
    with open(SEEN_PATH, "w") as f:
        json.dump(sorted(seen), f)


def load_existing():
    if not os.path.exists(OUTPUT_PATH):
        return []
    content = open(OUTPUT_PATH, encoding="utf-8").read()
    start = content.find("[")
    end = content.rfind("]") + 1
    if start == -1 or end == 0:
        return []
    try:
        return json.loads(content[start:end])
    except Exception:
        return []


def write_output(items):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = f"// Auto-generated by KarpTube scraper. Last updated: {ts}\nwindow.KARPTUBE_ITEMS = {json.dumps(items, indent=2, ensure_ascii=False)};\n"
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[karptube] Written {len(items)} items to karptube.js")


def make_item(uid, source, source_type, title, snippet, url, date_str):
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return {
        "id": uid,
        "source": source,
        "source_type": source_type,
        "title": (title or "")[:160],
        "snippet": (snippet or "")[:400],
        "url": url or "",
        "date": date_str or today,  # fall back to scrape date — web search has no pub date
        "scraped_at": datetime.now(timezone.utc).isoformat(),
    }


_RSS_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    ),
    "Accept": "application/rss+xml, application/atom+xml, application/xml, text/xml;q=0.9, */*",
}


def scrape_rss_feeds():
    """RSS: news sites, Substacks, Medium, YouTube channels, Reddit, Google News."""
    try:
        import feedparser
        import requests as req
    except ImportError:
        print("[karptube-rss] feedparser or requests not installed")
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(days=7)

    registry_feeds = source_registry.get_rss_sources(destinations=["karptube"])
    youtube_feeds = source_registry.get_youtube_sources()
    reddit_feeds = source_registry.get_reddit_sources()

    FEEDS = []
    for s in registry_feeds:
        FEEDS.append((s["name"], s["url"], s.get("type", "rss"), s.get("filter_palantir", True)))
    for s in youtube_feeds:
        if s.get("url") and "youtube.com/feeds" in s["url"]:
            FEEDS.append((s["name"], s["url"], "video", s.get("filter_palantir", False)))
    for s in reddit_feeds:
        FEEDS.append((s["name"], s["url"], "blog", s.get("filter_palantir", False)))

    items = []
    for name, url, source_type, must_mention in FEEDS:
        if not url:
            continue
        try:
            # Pre-fetch via requests for better redirect/encoding handling
            resp = req.get(url, timeout=20, headers=_RSS_HEADERS)
            if resp.status_code != 200:
                print(f"[karptube-rss] {name}: HTTP {resp.status_code}")
                continue
            feed = feedparser.parse(resp.content)
            if feed.bozo and not feed.entries:
                print(f"[karptube-rss] Failed to parse {name}: {feed.bozo_exception}")
                continue
            count = 0
            for entry in feed.entries[:30]:
                title = entry.get("title", "")
                summary = entry.get("summary", "") or entry.get("description", "") or ""
                link = entry.get("link", "")

                # Strip HTML
                import re
                summary_clean = re.sub(r"<[^>]+>", " ", summary)
                summary_clean = re.sub(r"\s+", " ", summary_clean).strip()[:400]

                combined = (title + " " + summary_clean).lower()
                if must_mention and "palantir" not in combined:
                    continue

                # Date filter
                published = entry.get("published_parsed") or entry.get("updated_parsed")
                date_str = ""
                if published:
                    try:
                        pub_dt = datetime(*published[:6], tzinfo=timezone.utc)
                        if pub_dt < cutoff:
                            continue
                        date_str = pub_dt.strftime("%Y-%m-%d")
                    except Exception:
                        pass
                else:
                    continue  # skip undated

                uid = hashlib.sha256(f"kt-rss-{link}".encode()).hexdigest()[:16]
                items.append(make_item(uid, name, source_type, title, summary_clean, link, date_str))
                count += 1
            print(f"[karptube-rss] {name}: {count} items")
        except Exception as e:
            print(f"[karptube-rss] Error {name}: {e}")

    return items


def scrape_web_search():
    """DuckDuckGo wide-net search — last week, many queries."""
    try:
        from ddgs import DDGS
    except ImportError:
        try:
            from duckduckgo_search import DDGS
        except ImportError:
            print("[karptube-ddg] ddgs not installed")
            return []

    registry_queries = source_registry.get_ddg_queries()
    queries = [(s["query"], s.get("type", "news")) for s in registry_queries]

    items = []
    with DDGS() as ddgs:
        for query, source_type in queries:
            try:
                results = ddgs.text(query, max_results=8, timelimit="w")  # last week
                count = 0
                for r in (results or []):
                    uid = hashlib.sha256(f"kt-ddg-{r.get('href', '')}".encode()).hexdigest()[:16]
                    items.append(make_item(
                        uid, f"Web — {query}", source_type,
                        r.get("title", "")[:160],
                        r.get("body", "")[:400],
                        r.get("href", ""),
                        "",
                    ))
                    count += 1
                print(f"[karptube-ddg] '{query}': {count} results")
                time.sleep(1.2)
            except Exception as e:
                print(f"[karptube-ddg] '{query}' failed: {e}")
                time.sleep(2)

    return items


def run():
    print(f"[karptube] Starting at {datetime.now(timezone.utc).isoformat()}Z")
    seen = load_seen()

    all_items = []

    print("\n=== RSS / YouTube / Reddit ===")
    all_items.extend(scrape_rss_feeds())

    print("\n=== Web Search ===")
    all_items.extend(scrape_web_search())

    # Deduplicate
    existing = load_existing()
    existing_ids = {i["id"] for i in existing}

    new_items = []
    for item in all_items:
        if not item.get("id") or not item.get("url"):
            continue
        if item["id"] in seen or item["id"] in existing_ids:
            continue
        new_items.append(item)
        seen.add(item["id"])

    print(f"\n[karptube] {len(new_items)} new items (from {len(all_items)} scraped)")

    # Newest first; 5000-item cap to preserve historical preload content
    merged = new_items + existing
    merged.sort(key=lambda x: x.get("date", "") or x.get("scraped_at", ""), reverse=True)
    merged = merged[:5000]

    write_output(merged)
    save_seen(seen)
    source_registry.save()
    print(f"[karptube] Done. Total: {len(merged)}")


if __name__ == "__main__":
    run()
