#!/usr/bin/env python3
"""
KarpTube scraper — wide-net Palantir media feed.
Pulls everything Palantir-related from news, RSS, YouTube, Reddit,
social, podcasts, newsletters, blogs. 7-day rolling window.
Writes to palantir-dashboard/karptube.js
"""
import hashlib
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD_DIR = os.path.join(ROOT, "palantir-dashboard")
OUTPUT_PATH = os.path.join(DASHBOARD_DIR, "karptube.js")
SEEN_PATH = os.path.join(os.path.dirname(__file__), "karptube_seen_ids.json")

sys.path.insert(0, os.path.dirname(__file__))


def load_seen():
    if os.path.exists(SEEN_PATH):
        with open(SEEN_PATH) as f:
            return set(json.load(f))
    return set()


def save_seen(seen):
    with open(SEEN_PATH, "w") as f:
        json.dump(sorted(seen), f)


def load_existing():
    if not os.path.exists(OUTPUT_PATH):
        return []
    content = open(OUTPUT_PATH, encoding="utf-8").read()
    start = content.find("[")
    end = content.rfind("]") + 1
    if start == -1 or end == 0:
        return []
    try:
        return json.loads(content[start:end])
    except Exception:
        return []


def write_output(items):
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = f"// Auto-generated by KarpTube scraper. Last updated: {ts}\nwindow.KARPTUBE_ITEMS = {json.dumps(items, indent=2, ensure_ascii=False)};\n"
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"[karptube] Written {len(items)} items to karptube.js")


def make_item(uid, source, source_type, title, snippet, url, date_str):
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return {
        "id": uid,
        "source": source,
        "source_type": source_type,
        "title": (title or "")[:160],
        "snippet": (snippet or "")[:400],
        "url": url or "",
        "date": date_str or today,  # fall back to scrape date — web search has no pub date
        "scraped_at": datetime.now(timezone.utc).isoformat(),
    }


def scrape_rss_feeds():
    """RSS: news sites, Substacks, Medium, YouTube channels, Reddit, Google News."""
    try:
        import feedparser
    except ImportError:
        print("[karptube-rss] feedparser not installed")
        return []

    cutoff = datetime.now(timezone.utc) - timedelta(days=7)

    FEEDS = [
        # News
        ("Google News — Palantir", "https://news.google.com/rss/search?q=palantir&hl=en-US&gl=US&ceid=US:en", "news", False),
        ("Breaking Defense", "https://breakingdefense.com/feed/", "news", True),
        ("Defense One", "https://www.defenseone.com/rss/all/", "news", True),
        ("C4ISRNET", "https://www.c4isrnet.com/arc/outboundfeeds/rss/", "news", True),
        ("FedScoop", "https://fedscoop.com/feed/", "news", True),
        ("War on the Rocks", "https://warontherocks.com/feed/", "news", True),
        ("Lawfare", "https://www.lawfaremedia.org/feed", "news", True),
        ("The Information", "https://www.theinformation.com/feed", "news", True),
        # Newsletters / Substacks
        ("Shyam Sankar", "https://shyamsankar.com/feed", "newsletter", False),
        ("Amit Kukreja", "https://amitsdeepdives.substack.com/feed", "newsletter", True),
        ("Arny Trezzi", "https://arnytrezzi.substack.com/feed", "newsletter", True),
        ("Import AI (Jack Clark)", "https://importai.substack.com/feed", "newsletter", True),
        ("Big Technology", "https://bigtechnology.substack.com/feed", "newsletter", True),
        ("Nonzero Newsletter", "https://nonzero.substack.com/feed", "newsletter", True),
        ("First Breakfast", "https://firstbreakfast.substack.com/feed", "newsletter", True),
        ("Crossing the Valley", "https://crossingthevalley.substack.com/feed", "newsletter", True),
        # Blogs / Medium
        ("Palantir (Medium)", "https://medium.com/feed/palantir", "blog", True),
        # Reddit
        ("r/palantir", "https://www.reddit.com/r/palantir/.rss", "blog", False),
        ("r/PLTR", "https://www.reddit.com/r/PLTR/.rss", "blog", False),
        # YouTube (RSS)
        ("Palantir Tech (YouTube)", "https://www.youtube.com/feeds/videos.xml?channel_id=UCXDlpGEFdP4i_JBDpQoAOyg", "video", False),
    ]

    items = []
    for name, url, source_type, must_mention in FEEDS:
        try:
            feed = feedparser.parse(url)
            if feed.bozo and not feed.entries:
                print(f"[karptube-rss] Failed to parse {name}")
                continue
            count = 0
            for entry in feed.entries[:30]:
                title = entry.get("title", "")
                summary = entry.get("summary", "") or entry.get("description", "") or ""
                link = entry.get("link", "")

                # Strip HTML
                import re
                summary_clean = re.sub(r"<[^>]+>", " ", summary)
                summary_clean = re.sub(r"\s+", " ", summary_clean).strip()[:400]

                combined = (title + " " + summary_clean).lower()
                if must_mention and "palantir" not in combined:
                    continue

                # Date filter
                published = entry.get("published_parsed") or entry.get("updated_parsed")
                date_str = ""
                if published:
                    try:
                        pub_dt = datetime(*published[:6], tzinfo=timezone.utc)
                        if pub_dt < cutoff:
                            continue
                        date_str = pub_dt.strftime("%Y-%m-%d")
                    except Exception:
                        pass
                else:
                    continue  # skip undated

                uid = hashlib.sha256(f"kt-rss-{link}".encode()).hexdigest()[:16]
                items.append(make_item(uid, name, source_type, title, summary_clean, link, date_str))
                count += 1
            print(f"[karptube-rss] {name}: {count} items")
        except Exception as e:
            print(f"[karptube-rss] Error {name}: {e}")

    return items


def scrape_web_search():
    """DuckDuckGo wide-net search — last week, many queries."""
    try:
        from ddgs import DDGS
    except ImportError:
        try:
            from duckduckgo_search import DDGS
        except ImportError:
            print("[karptube-ddg] ddgs not installed")
            return []

    queries = [
        ("Palantir news", "news"),
        ("Palantir contract award", "news"),
        ("Palantir AIP government defense", "news"),
        ("Palantir earnings revenue", "news"),
        ("Palantir Alex Karp interview", "news"),
        ("Palantir Shyam Sankar", "news"),
        ("Palantir Peter Thiel", "news"),
        ("Palantir military AI", "news"),
        ("Palantir DOGE government", "news"),
        ("Palantir stock PLTR analysis", "article"),
        ("Palantir podcast interview 2026", "podcast"),
        ("Palantir Technologies announcement", "news"),
    ]

    items = []
    with DDGS() as ddgs:
        for query, source_type in queries:
            try:
                results = ddgs.text(query, max_results=8, timelimit="w")  # last week
                count = 0
                for r in (results or []):
                    uid = hashlib.sha256(f"kt-ddg-{r.get('href', '')}".encode()).hexdigest()[:16]
                    items.append(make_item(
                        uid, f"Web — {query}", source_type,
                        r.get("title", "")[:160],
                        r.get("body", "")[:400],
                        r.get("href", ""),
                        "",
                    ))
                    count += 1
                print(f"[karptube-ddg] '{query}': {count} results")
                time.sleep(1.2)
            except Exception as e:
                print(f"[karptube-ddg] '{query}' failed: {e}")
                time.sleep(2)

    return items


def run():
    print(f"[karptube] Starting at {datetime.now(timezone.utc).isoformat()}Z")
    seen = load_seen()

    all_items = []

    print("\n=== RSS / YouTube / Reddit ===")
    all_items.extend(scrape_rss_feeds())

    print("\n=== Web Search ===")
    all_items.extend(scrape_web_search())

    # Deduplicate
    existing = load_existing()
    existing_ids = {i["id"] for i in existing}

    new_items = []
    for item in all_items:
        if not item.get("id") or not item.get("url"):
            continue
        if item["id"] in seen or item["id"] in existing_ids:
            continue
        new_items.append(item)
        seen.add(item["id"])

    print(f"\n[karptube] {len(new_items)} new items (from {len(all_items)} scraped)")

    # Newest first, rolling 1000-item window
    merged = new_items + existing
    merged.sort(key=lambda x: x.get("date", "") or x.get("scraped_at", ""), reverse=True)
    merged = merged[:1000]

    write_output(merged)
    save_seen(seen)
    print(f"[karptube] Done. Total: {len(merged)}")


if __name__ == "__main__":
    run()
