#!/usr/bin/env python3
"""
Palantir Dashboard — Daily Scraper
Collects new contract data and media mentions, writes to pending.js
"""
import json
import os
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD_DIR = os.path.join(ROOT, "palantir-dashboard")
CONFIG_PATH = os.path.join(DASHBOARD_DIR, "sources_config.json")
PENDING_JS_PATH = os.path.join(DASHBOARD_DIR, "pending.js")
KARPTUBE_JS_PATH = os.path.join(DASHBOARD_DIR, "karptube.js")
SEEN_PATH = os.path.join(os.path.dirname(__file__), "seen_ids.json")

sys.path.insert(0, os.path.dirname(__file__))

from scrapers import (
    us_spending, uk_contracts, eu_ted, canada,
    australia, ukraine_prozorro, sec_edgar, palantir_ir,
    rss_feeds, web_search,
)
from screener import is_inbox_item
import source_registry


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_seen_ids():
    if os.path.exists(SEEN_PATH):
        with open(SEEN_PATH, "r") as f:
            return set(json.load(f))
    return set()


def save_seen_ids(seen):
    with open(SEEN_PATH, "w") as f:
        json.dump(sorted(seen), f)


def load_existing_pending():
    if not os.path.exists(PENDING_JS_PATH):
        return []
    with open(PENDING_JS_PATH, "r", encoding="utf-8") as f:
        content = f.read()
    # Extract JSON array from window.PENDING_ITEMS = [...];
    start = content.find("[")
    end = content.rfind("]") + 1
    if start == -1 or end == 0:
        return []
    try:
        return json.loads(content[start:end])
    except json.JSONDecodeError:
        return []


def load_existing_karptube():
    if not os.path.exists(KARPTUBE_JS_PATH):
        return []
    with open(KARPTUBE_JS_PATH, "r", encoding="utf-8") as f:
        content = f.read()
    start = content.find("[")
    end = content.rfind("]") + 1
    if start == -1 or end == 0:
        return []
    try:
        return json.loads(content[start:end])
    except json.JSONDecodeError:
        return []


def write_karptube_js(items):
    ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    json_str = json.dumps(items, indent=2, ensure_ascii=False)
    content = f"// Auto-generated by scraper. Last updated: {ts}\nwindow.KARPTUBE_ITEMS = {json_str};\n"
    with open(KARPTUBE_JS_PATH, "w", encoding="utf-8") as f:
        f.write(content)


def write_pending_js(items):
    ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    json_str = json.dumps(items, indent=2, ensure_ascii=False)
    content = f"// Auto-generated by scraper. Last updated: {ts}\nwindow.PENDING_ITEMS = {json_str};\n"
    with open(PENDING_JS_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"\n[main] Written {len(items)} items to pending.js")


def run():
    print(f"[main] Starting scraper run at {datetime.utcnow().isoformat()}Z")
    config = load_config()
    seen_ids = load_seen_ids()

    all_items = []

    # --- Tier 1: Contract APIs ---
    print("\n=== Contract APIs ===")
    for scraper_fn in [us_spending.scrape, uk_contracts.scrape, eu_ted.scrape,
                       canada.scrape, australia.scrape, ukraine_prozorro.scrape]:
        try:
            all_items.extend(scraper_fn())
        except Exception as e:
            print(f"[main] Scraper {scraper_fn.__module__} failed: {e}")

    # --- Tier 2: Official disclosures ---
    print("\n=== Official Disclosures ===")
    for scraper_fn in [sec_edgar.scrape, palantir_ir.scrape]:
        try:
            all_items.extend(scraper_fn())
        except Exception as e:
            print(f"[main] Scraper {scraper_fn.__module__} failed: {e}")

    # --- Tier 3: RSS feeds ---
    print("\n=== RSS Feeds ===")
    try:
        # Load source registry
        registry = source_registry.load()
        # RSS sources with destination screened or inbox
        screened_rss = source_registry.get_rss_sources(destinations=["inbox", "screened"])
        all_items.extend(rss_feeds.scrape(screened_rss))
    except Exception as e:
        print(f"[main] RSS scraper failed: {e}")

    # --- Tier 3: Web/X search ---
    print("\n=== Web / X Search ===")
    try:
        # X handles with destination screened or inbox
        screened_x = source_registry.get_x_handles(destinations=["inbox", "screened"])
        all_items.extend(web_search.scrape(screened_x))
    except Exception as e:
        print(f"[main] Web search scraper failed: {e}")

    # --- Screen & route ---
    # Architecture: KarpTube = universal feed (everything lands here).
    # Screener is an ELEVATOR, not a gatekeeper — it identifies items that
    # ALSO deserve to appear in Inbox (deal/contract signals) or Financials
    # (earnings signals). Routing is additive, never exclusive.
    print("\n=== Screening & Routing ===")

    existing_pending = load_existing_pending()
    existing_pending_ids = {item["id"] for item in existing_pending}

    existing_karptube = load_existing_karptube()
    existing_karptube_ids = {item["id"] for item in existing_karptube}

    new_inbox = []
    new_karptube = []

    for item in all_items:
        if not item.get("id") or not item.get("url"):
            continue
        if item["id"] in seen_ids:
            continue

        should_inbox, score, reason = is_inbox_item(item)
        item["screen_score"] = score
        item["screen_reason"] = reason
        seen_ids.add(item["id"])

        # ── Circle 1: KarpTube (universal — everything lands here) ──────────
        if item["id"] not in existing_karptube_ids:
            new_karptube.append(item)
            existing_karptube_ids.add(item["id"])  # prevent double-add within run

        # ── Circle 2: Inbox (elevation — deal/contract items ALSO go here) ──
        if should_inbox:
            if item["id"] not in existing_pending_ids:
                new_inbox.append(item)

    print(f"[main] {len(new_karptube)} -> KarpTube (all), "
          f"{len(new_inbox)} -> Inbox (elevated deal items), "
          f"from {len(all_items)} scraped")

    # Write pending.js (Inbox — deal-elevated items only)
    merged_pending = (new_inbox + existing_pending)[:500]
    write_pending_js(merged_pending)

    # Write karptube.js (everything)
    merged_karptube = new_karptube + existing_karptube
    merged_karptube.sort(
        key=lambda x: x.get("date", "") or x.get("scraped_at", ""),
        reverse=True,
    )
    merged_karptube = merged_karptube[:1000]
    write_karptube_js(merged_karptube)
    print(f"[main] KarpTube: {len(merged_karptube)} total ({len(new_karptube)} new)")

    save_seen_ids(seen_ids)

    # Update stats and save registry
    # (Basic stats - we don't have per-source counts easily, update total run time)
    source_registry.save()

    print(f"[main] Done. Inbox: {len(merged_pending)} | KarpTube: {len(existing_karptube) + len(new_karptube)}")


if __name__ == "__main__":
    run()
