#!/usr/bin/env python3
"""
Palantir Dashboard — Daily Scraper
Collects new contract data and media mentions, writes to pending.js
"""
import json
import os
import sys
from datetime import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD_DIR = os.path.join(ROOT, "palantir-dashboard")
CONFIG_PATH = os.path.join(DASHBOARD_DIR, "sources_config.json")
PENDING_JS_PATH = os.path.join(DASHBOARD_DIR, "pending.js")
SEEN_PATH = os.path.join(os.path.dirname(__file__), "seen_ids.json")

sys.path.insert(0, os.path.dirname(__file__))

from scrapers import (
    us_spending, uk_contracts, eu_ted, canada,
    australia, ukraine_prozorro, sec_edgar, palantir_ir,
    rss_feeds, web_search,
)


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def load_seen_ids():
    if os.path.exists(SEEN_PATH):
        with open(SEEN_PATH, "r") as f:
            return set(json.load(f))
    return set()


def save_seen_ids(seen):
    with open(SEEN_PATH, "w") as f:
        json.dump(sorted(seen), f)


def load_existing_pending():
    if not os.path.exists(PENDING_JS_PATH):
        return []
    with open(PENDING_JS_PATH, "r", encoding="utf-8") as f:
        content = f.read()
    # Extract JSON array from window.PENDING_ITEMS = [...];
    start = content.find("[")
    end = content.rfind("]") + 1
    if start == -1 or end == 0:
        return []
    try:
        return json.loads(content[start:end])
    except json.JSONDecodeError:
        return []


def write_pending_js(items):
    ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
    json_str = json.dumps(items, indent=2, ensure_ascii=False)
    content = f"// Auto-generated by scraper. Last updated: {ts}\nwindow.PENDING_ITEMS = {json_str};\n"
    with open(PENDING_JS_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"\n[main] Written {len(items)} items to pending.js")


def run():
    print(f"[main] Starting scraper run at {datetime.utcnow().isoformat()}Z")
    config = load_config()
    seen_ids = load_seen_ids()

    all_items = []

    # --- Tier 1: Contract APIs ---
    print("\n=== Contract APIs ===")
    for scraper_fn in [us_spending.scrape, uk_contracts.scrape, eu_ted.scrape,
                       canada.scrape, australia.scrape, ukraine_prozorro.scrape]:
        try:
            all_items.extend(scraper_fn())
        except Exception as e:
            print(f"[main] Scraper {scraper_fn.__module__} failed: {e}")

    # --- Tier 2: Official disclosures ---
    print("\n=== Official Disclosures ===")
    for scraper_fn in [sec_edgar.scrape, palantir_ir.scrape]:
        try:
            all_items.extend(scraper_fn())
        except Exception as e:
            print(f"[main] Scraper {scraper_fn.__module__} failed: {e}")

    # --- Tier 3: RSS feeds ---
    print("\n=== RSS Feeds ===")
    try:
        all_items.extend(rss_feeds.scrape(config["rss_feeds"]))
    except Exception as e:
        print(f"[main] RSS scraper failed: {e}")

    # --- Tier 3: Web/X search ---
    print("\n=== Web / X Search ===")
    try:
        all_items.extend(web_search.scrape(config["x_accounts"]))
    except Exception as e:
        print(f"[main] Web search scraper failed: {e}")

    # --- Merge & deduplicate ---
    print("\n=== Merging ===")

    # Load existing pending to preserve items already in the list
    existing = load_existing_pending()
    existing_ids = {item["id"] for item in existing}

    # Only add items not seen before AND not already in pending
    new_items = []
    for item in all_items:
        if not item.get("id") or not item.get("url"):
            continue
        if item["id"] in seen_ids:
            continue
        if item["id"] in existing_ids:
            continue
        new_items.append(item)
        seen_ids.add(item["id"])

    print(f"[main] {len(new_items)} new items (from {len(all_items)} total scraped)")

    # Prepend new items to existing pending list (newest first)
    merged = new_items + existing

    # Keep a rolling window: max 500 items in pending.js
    merged = merged[:500]

    write_pending_js(merged)
    save_seen_ids(seen_ids)

    print(f"[main] Done. Total pending: {len(merged)}")


if __name__ == "__main__":
    run()
