// Auto-generated by KarpTube scraper. Last updated: 2026-03-10T06:04:46Z
window.KARPTUBE_ITEMS = [
  {
    "id": "6574de95bd4a20e5",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "Pentagon Ban On Claude Tests Palantir’s Defense Reliability ...",
    "snippet": "1 day ago ·The Pentagon has banned Anthropic as a national security supply chain risk, immediately affecting its Claude AI model. PalantirTechnologies(NasdaqGS:PLTR) must quickly remove Claude from key U.S. defense platforms and rebuild affected workflows. The transition is causing short term disruption to sensitive government contracts, including potential outages and project delays. For investor",
    "url": "https://simplywall.st/stocks/us/software/nasdaq-pltr/palantir-technologies/news/pentagon-ban-on-claude-tests-palantirs-defense-reliability-a",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "a7a05c831c42d1c1",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "Palantir Confronts Pentagon AI Ban As Defense Demand And ...",
    "snippet": "5 days ago ·The Pentagon has ordered the removal of Anthropic's Claude AI model from U.S. government programs that usePalantirsoftware.Palantirmust rebuild parts of key military platforms that relied...",
    "url": "https://finance.yahoo.com/news/palantir-confronts-pentagon-ai-ban-031511965.html?fr=sycsrp_catchall",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "249f0cc16485e5e9",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "Palantir Technologies (PLTR) Is Up 14.6% After Pentagon AI ...",
    "snippet": "3 days ago ·PalantirTechnologies' narrative projects $10.8 billion revenue and $3.6 billion earnings by 2028. This requires 40.7% yearly revenue growth and about a $2.5 billion earnings increase from $1.1 billion today.",
    "url": "https://www.sahmcapital.com/news/content/palantir-technologies-pltr-is-up-146-after-pentagon-ai-shift-boosts-defense-workloads-has-the-bull-case-changed-2026-03-07",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "79d14f621b162a22",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "PLTR: Palantir Technologies Inc - Stock Price, Quote ... - CNBC",
    "snippet": "1 day ago ·Get PalantirTechnologiesInc (PLTR:NASDAQ) real-time stock quotes, news, price and financial information fromCNBC.",
    "url": "https://www.cnbc.com/quotes/PLTR",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "2c0203d3fa2839d8",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "Palantir Technologies (PLTR) Stock Latest News - PLTR News Today",
    "snippet": "5 days ago ·PalantirTechnologies(PLTR) delivered strong FQ4 2025 results, beating estimates and sustaining double-digit YOY growth, yet shares sold off with the broader software sector.",
    "url": "https://www.financecharts.com/stocks/PLTR/news",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "690f74c479b1146f",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "Palantir’s departure will mean economic pain for Colorado ...",
    "snippet": "6 days ago ·DENVER — As Colorado’s largest public company Palantirannouncedit would relocate its headquarters from Denver to the Miami area last month, the research group Common Sense Institute has released a report to try to quantify the economic impact.",
    "url": "https://www.denver7.com/money/business-news/departure-of-colorados-largest-public-company-palantir-could-mean-economic-pain-new-report-says",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "0a55ba4432203916",
    "source": "Web — Palantir Technologies announcement",
    "source_type": "news",
    "title": "March 2025 • Announcements • Palantir",
    "snippet": "We are excited to announce three new enhancements to experiments in thePalantirplatform: MLflow ↗ integration, image logging, and a parallel ...",
    "url": "https://www.palantir.com/docs/foundry/announcements/2025-03",
    "date": "",
    "scraped_at": "2026-03-10T06:04:44.915985+00:00"
  },
  {
    "id": "f57f780bb02b7383",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "Palantir (PLTR) 2026: The Rise of the Logic Layer and the ...",
    "snippet": "5 days ago ·As we enter the first quarter of2026,PalantirTechnologies Inc. (NYSE: PLTR) has transformed from a controversial, secretive data-mining firm into what many analysts now call the \"Operating System of the Modern Enterprise.\"",
    "url": "https://markets.financialcontent.com/postgazette/article/finterra-2026-3-5-palantir-pltr-2026-the-rise-of-the-logic-layer-and-the-agentic-ai-revolution",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "7e7ce16cb4312efd",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "Prediction: This Is How Much Further Palantir Stock Could ...",
    "snippet": "23 hours ago ·ThePalantirTechnologies(NASDAQ: PLTR) bubble is finally beginning to deflate: Shares in the artificial intelligence (AI)-driven data analytics company are now down 24% from the all-time high of ...",
    "url": "https://finance.yahoo.com/news/prediction-much-further-palantir-stock-063800727.html?fr=sycsrp_catchall",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "214aa660d2a9a1c9",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "Massive News: Palantir's 2026 Forecast Could Supercharge ...",
    "snippet": "5 days ago ·Palantir's2026guidance could mark a turning point, but with valuation stretched, the next few quarters may decide everything.Palantir(PLTR +3.03%) just delivered a forecast that could...",
    "url": "https://www.fool.com/investing/2026/03/04/massive-news-palantirs-2026-forecast-could-superch/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "960fed2921f78ab0",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "User | times-online.com - Palantir (PLTR) 2026: The Rise of ...",
    "snippet": "4 days ago ·As we enter the first quarter of2026,PalantirTechnologies Inc. (NYSE: PLTR) has transformed from a controversial, secretive data-mining firm into what many analysts now call the \"Operating System of the Modern Enterprise.\"",
    "url": "https://markets.financialcontent.com/times-online/article/finterra-2026-3-5-palantir-pltr-2026-the-rise-of-the-logic-layer-and-the-agentic-ai-revolution",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "5f615039f48a3427",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "PLTR Forecast: 2026, 2027 & Long-Term AI Predictions",
    "snippet": "19 hours ago ·Explore detailed predictions for2026,2027, and long-term projections, including daily price targets, monthly trends, technical analysis, and market insights to inform your investment decisions.",
    "url": "https://midforex.com/stocks/pltr-forecast",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "cb39f985c1c15d84",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "On the Air With Palantir, Ep. 01: Successful Strategies for",
    "snippet": "We're very excited to kick-off our newpodcastcalled On the Air withPalantirhosted by Allison Manley, and welcome you to listen to our first ...",
    "url": "https://www.palantir.net/blog/air-palantir-podcast-ep-01",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "426bd69df63db6bc",
    "source": "Web — Palantir podcast interview 2026",
    "source_type": "podcast",
    "title": "On The Air With Palantir, Ep. 7: Getting Started in Drupal |",
    "snippet": "Welcome to the latest episode of On the Air withPalantir, a long-formpodcastbyPalantir.net where we go in-depth on topics related to the business ...",
    "url": "https://www.palantir.net/podcast/air-palantir-ep-7-getting-started-drupal",
    "date": "",
    "scraped_at": "2026-03-10T06:04:40.151379+00:00"
  },
  {
    "id": "5c0db8f49331002a",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir Stock (PLTR) - Complete Investment Guide & Price",
    "snippet": "Palantirstocktrades on the NASDAQ under ticker symbol “PLTR,” making it accessible through virtually any brokerage platform:",
    "url": "https://www.greatinspire.com/palantir-stock-the-complete-investment-guide-for-ai-and-data-analytics/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "ed79efbbbafccac1",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir (PLTR) AI Stock Analysis Statistics 2026",
    "snippet": "This AIstockanalysisforPalantiris not up to date. ... Given these conflicting signals, the overall recommendation forPalantir’sstockwould ...",
    "url": "https://altindex.com/ticker/pltr/ai-stock-analysis",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "05f5aa5b8b9d5473",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "PLTR Stock - Palantir Technologies Inc. Price & Analysis |",
    "snippet": "In a Category of One,’ Says Analyst asPalantirStock(PLTR... AI Disrupting AI’: Top Investor WarnsPalantirStock(PLTR) Could Be in Trouble",
    "url": "https://marketxls.com/stocks/pltr",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "79839c5065ef3712",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir Technologies Inc. (PLTR) - Stock Analysis |",
    "snippet": "With an overall rank of 90 ,PLTRis among the top 10% ofstockson our website when it comes to balancing risk and reward.",
    "url": "https://portfolioslab.com/symbol/PLTR",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "e647acde4841cfcd",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir (PLTR) Stock Price & Analysis: Can The Data Giant",
    "snippet": "Palantir(PLTR)StockPriceAnalysis: Can The Data Giant Weather The Tariff Storm? ...PalantirTechnologies saw itsstockplummet on Friday as ...",
    "url": "https://mtrushmorecrypto.com/palantir-pltr-stock-price-analysis-can-the-data-giant-weather-the-tariff-storm/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "0e4aacaa31c6586b",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir Technologies (PLTR) | Trefis",
    "snippet": "PalantirTechnologies (PLTR)stockhas lost about 10% since 11/30/2025 because of the following key factors: 1. ...PalantirTechnologies'sstock...",
    "url": "https://www.trefis.com/data/companies/PLTR/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "92c1caaeedd3835c",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "Palantir Technologies (PLTR) Stock Price History Chart &",
    "snippet": "PalantirTechnologies (PLTR)StockChart & TechnicalAnalysisGraph ...PalantirTechnologies s advanced charting and technicalanalysistool ...",
    "url": "https://www.tipranks.com/stocks/pltr/stock-charts",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "7731ee7feb547e15",
    "source": "Web — Palantir stock PLTR analysis",
    "source_type": "article",
    "title": "PLTR Stock | Where Does It Go From Here? Full Stock Analysis",
    "snippet": "PalantirTechnologies (PLTR)StockAnalysis: Is It ...PLTRStock, also known asPalantir, has been one of the most searchedstockson the internet .",
    "url": "https://thebrownreport.com/pltr-stock-where-does-it-go-from-here-full-stock-analysis/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:35.238277+00:00"
  },
  {
    "id": "60fae01919a6fa38",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir CEO Alex Karp Calls DOGE a 'Revolution,' Welcomes",
    "snippet": "Palantirhas contracts withgovernmentorganizations, both in the US and abroad, many of which use its software for military operations and ...",
    "url": "https://www.businessinsider.com/palantir-ceo-alex-karp-doge-revolution-disruption-earnings-call-2025-2",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "af84ef8ed0233142",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir’s Deepening Government Ties Spark Fears of",
    "snippet": "According to the Times report (citing six allegedgovernmentofficials andPalantiremployees), the company is also in discussions with the ...",
    "url": "https://discernreport.com/palantirs-deepening-government-ties-spark-fears-of-centralized-surveillance/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "eff7e683aed76e37",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir Is Extending Its Reach Even Further Into Government |",
    "snippet": "...governmentbranch,Palantirwill train and certify at least 1,000 Accenture workers on its Foundry software as well as its AI tech, according to an ...",
    "url": "https://www.wired.com/story/palantir-government-contracting-push/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "9fe27672c5d28ccc",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir | Latest News, Photos & Videos | WIRED",
    "snippet": "ADOGERecruiter Is Staffing a Project to Deploy AI Agents Across the USGovernment...PalantirIs HelpingDOGEWith a Massive IRS Data Project",
    "url": "https://www.wired.com/tag/palantir/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "311a58a6970d303a",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir's Deepening Government Ties Spark Fears Of",
    "snippet": "According to the report, since Donald Trump took officePalantirhas received over $113 million ingovernmentspending - which doesn t include a $795 ...",
    "url": "https://www.zerohedge.com/political/palantirs-deepening-government-ties-spark-fears-centralized-surveillance",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "19382b418dbb870e",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir’s Deepening Government Ties Spark Fears of",
    "snippet": "According to the Times report (citing six allegedgovernmentofficials andPalantiremployees), the company is also in discussions with the ...",
    "url": "https://americafirstreport.com/palantirs-deepening-government-ties-spark-fears-of-centralized-surveillance/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "4fa9f012b98c0b45",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir’s Deepening Government Ties Spark Fears of",
    "snippet": "According to the Times report (citing six allegedgovernmentofficials andPalantiremployees), the company is also in discussions with the ...",
    "url": "https://jdrucker.com/palantirs-deepening-government-ties-spark-fears-of-centralized-surveillance/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "9361245ba13be08e",
    "source": "Web — Palantir DOGE government",
    "source_type": "news",
    "title": "Palantir's Market Surge Amid Government Reforms",
    "snippet": "GovernmentEfficiency Reforms: Elon Musk’sDOGEinitiative aims to cut costs and enhance operational transparency.",
    "url": "https://theentrepreneurinsights.com/palantirs-market-surge-amid-government-reforms/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:31.467631+00:00"
  },
  {
    "id": "d2cc97f83e1d8453",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "Inside Maven, Palantir's Military Brain Built on Claude",
    "snippet": "1 day ago ·While Google agonized over the ethics ofmilitaryAI,Palantir’s CEO Alex Karp argued it was the tech industry’s patriotic duty to serve themilitary.",
    "url": "https://www.linkedin.com/pulse/inside-maven-palantirs-military-brain-built-claude-anthony-maio-bd6ee",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "b8052fd368765852",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "Florida tech firm Palantir plays key role in 'Epic Fury ...",
    "snippet": "6 days ago ·ControversialAIdata giantPalantirTechnologies recently moved its headquarters to Miami from Denver. Here's how it's helping the U.S.military.PalantirTechnologies'AIis playing a...",
    "url": "https://www.usatoday.com/story/news/state/2026/03/04/florida-tech-firm-palantir-plays-key-role-in-epic-fury-attack-on-iran/88952660007/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "eda76130d27012de",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "Palantir Weighs Pentagon AI Setback Against Expanding Defense ...",
    "snippet": "4 days ago ·PalantirTechnologies (NasdaqGS:PLTR) is being required to remove Anthropic's ClaudeAImodels from key U.S.militarysoftware platforms following a Pentagon directive.",
    "url": "https://simplywall.st/stocks/us/software/nasdaq-pltr/palantir-technologies/news/palantir-weighs-pentagon-ai-setback-against-expanding-defens",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "6a9d7a67233f2537",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "How Palantir and Anthropic AI helped the US hit 1,000 Iran ...",
    "snippet": "4 days ago ·US military usedPalantir’sMavenAIsystem with Anthropic’s Claude to generate and prioritise targets during Iran strikes.",
    "url": "https://www.moneycontrol.com/world/how-palantir-and-anthropic-ai-helped-the-us-hit-1-000-iran-targets-in-24-hours-article-13853331.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "fd753a8c0dbca4d1",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "Palantir Faces Technical Hurdle as Pentagon Shifts AI ...",
    "snippet": "5 days ago ·A recent U.S. government directive is creating a significant operational challenge forPalantirTechnologies Inc. The Trump administration’s decision to blockAIfirm Anthropic from the defense sector has forcedPalantirto initiate a major rebuild of its Maven Smart Systemsmilitaryintelligence ...",
    "url": "https://www.newscase.com/palantir-faces-technical-hurdle-as-pentagon-shifts-ai-suppliers/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "0fd65c14fd3e712d",
    "source": "Web — Palantir military AI",
    "source_type": "news",
    "title": "Palantir Technologies Launch AI Platform for Military",
    "snippet": "According toPalantir, AIP enablesmilitaryoperators to pose questions to theAI, such as identifying enemy units in the region, requesting high ...",
    "url": "https://www.analyticsvidhya.com/blog/2023/05/palantir-technologies-launch-artificial-intelligence-platform-for-military-decision-making/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:27.675919+00:00"
  },
  {
    "id": "74f53c3b5063747e",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "How Peter Thiel’s Palantir Helped the NSA Spy on the World",
    "snippet": "... sector expertise and new strategic friendship with Silicon Valley billionaire investorPeterThiel, whose controversial (and opaque) companyPalantir...",
    "url": "https://theintercept.com/2017/02/22/how-peter-thiels-palantir-helped-the-nsa-spy-on-the-whole-world/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "63b801d153bf4a2c",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "Peter Thiel’s Palantir Used to Bust Migrant Children’s",
    "snippet": "PeterThiel’sPalantirWas Used to Bust Relatives of Migrant Children, New Documents Show ...Palantir, the CIA-funded data analysis company ...",
    "url": "https://theintercept.com/2019/05/02/peter-thiels-palantir-was-used-to-bust-hundreds-of-relatives-of-migrant-children-new-documents-show/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "c648a9f2e4975469",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "Palantir: Peter Thiel’s Data-Mining Firm Helps DOGE Build",
    "snippet": "Palantir:PeterThiel’ s Data-Mining Firm Helps DOGE Build Master Database to Surveil, Track Immigrants ... withPeterThieland hisPalantir...",
    "url": "https://www.democracynow.org/2025/6/3/makena_kelly",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "3c4a0197fdfdd889",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "How Palantir, Peter Thiel's Secretive Data Company, Pushed",
    "snippet": "PalantirTechnologies was founded in 2004 by a group of investors and technologists including its current CEO, Alex Karp, andPeterThiel, a ...",
    "url": "https://www.wired.com/story/how-peter-thiels-secretive-data-company-pushed-into-policing/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "0dae941241287555",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "Palantir 2025: Peter Thiel and Alex Karp Embody Trump's Era",
    "snippet": "Palantirco-foundersPeterThieland Alex Karp neatly embody the zeitgeist of 2025 withPalantir’ s use of AI for ICE and the IDF, their Trump ...",
    "url": "https://www.nakedcapitalism.com/2025/09/palantir-peter-thiel-alex-karp-antichrist-ai-ice-trump-vance-epstein.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "c5cd9249a1f3cb45",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "Peter Thiel: From Gaza AI War Criminal To White House Puppet",
    "snippet": "These scenes – altogether too familiar today – come enabled by German-American tech billionairePeterThieland his company,Palantir, whose ...",
    "url": "https://www.mintpressnews.com/peter-thiel-gaza-ai-war-white-house/288372/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "ecda3b26e00ed678",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "How Palantir Became a Front-Runner for the UK’s",
    "snippet": "Europe | HowPeterThiel’sPalantirPushed Toward the Heart of U.K. ... HowPeterThiel’sPalantirPushed Toward the Heart of U.K.",
    "url": "https://www.nytimes.com/2023/09/29/world/europe/uk-nhs-palantir.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "0c9dab707ac8d5e7",
    "source": "Web — Palantir Peter Thiel",
    "source_type": "news",
    "title": "What is Peter Thiel's Role in Palantir's Rise",
    "snippet": "PeterThielis a co-founder ofPalantirTechnologies, which he established in 2003 with Alex Karp , Stephen Cohen, and others.",
    "url": "https://www.ceotodaymagazine.com/2025/08/peter-thiels-secretive-ai-empire/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:22.200945+00:00"
  },
  {
    "id": "a4015f6c86581118",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "Who is Shyam Sankar? The billionaire technologist driving",
    "snippet": "PalantirCTOShyamSankarreacts as President Donald Trump delivers remarks during the Winning the AI Race Summit in Washington.",
    "url": "https://www.hindustantimes.com/business/who-is-shyam-sankar-the-billionaire-technologist-driving-palantirs-aiboom-101754369085280.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "1ca3eaeb59275bec",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "Palantir's Shyam Sankar on Power, Purpose, and Patriotism",
    "snippet": "ShyamSankar’s narrative paints a stark, even audacious, vision:Palantiras a cornerstone of a re-industrialized, technologically advanced, and ...",
    "url": "https://carringtonjournal.com/palantirs-shyam-sankar-on-power-purpose-and-patriotism/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "4d0ac91f53f92c9d",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "SRS #190 Shyam Sankar - Chief Technology Officer of Palantir:",
    "snippet": "SRSShyamSankar- Chief Technology Officer ofPalantir: The Future of ...ShyamSankaris the Chief Technology Officer atPalantirTechnologies.",
    "url": "https://shawnryanshow.com/blogs/the-shawn-ryan-show/srs-190-shyam-sankar-chief-technology-officer-of-palantir-technologies",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "dd6fe2cc7fa02159",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "The Patriot: Shyam Sankar of Palantir | RealClearPolitics",
    "snippet": "The Patriot:ShyamSankarofPalantir... For two decades,ShyamSankarhas been the most important but hidden figure behindPalantir.",
    "url": "https://www.realclearpolitics.com/2026/02/26/the_patriot_shyam_sankar_of_palantir_692676.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "7a6bc893e412bde8",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "About - Shyam Sankar",
    "snippet": "ShyamSankaris the Chief Technology Officer and Executive Vice President ofPalantirTechnologies. ... JoiningPalantiras employeeShyamenvisaged ...",
    "url": "https://www.shyamsankar.com/about",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "73e2522e15f8317e",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "PALANTIR CTO SHYAM SANKAR: The American people are being lied",
    "snippet": "Home Top StoriesPALANTIRCTOSHYAMSANKAR: The American people are being lied to about... ...ShyamSankaris the chief technology officer and ...",
    "url": "https://hdflashnews.com/2026/02/02/palantir-cto-shyam-sankar-the-american-people-are-being-lied-to-about-ai/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "457474aeaa8c964b",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "In conversation with Palantir CTO Shyam Sankar on his vision",
    "snippet": "Palantir's Chief Technology Officer,ShyamSankar... Are we trying to fix the system or are we trying to win? ” ,PalantirCTOShyamSankar.",
    "url": "https://www.apexdefense.org/past-engagements/conversation-palantir-cto-shyam-sankar-vision-defence-industrial-base",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "78dbfd32e027b553",
    "source": "Web — Palantir Shyam Sankar",
    "source_type": "news",
    "title": "Who is Shyam Sankar: Early Life, Career, and Net Worth |",
    "snippet": "In addition to his role atPalantir,ShyamSankarserves as Chairman of Ginkgo Bioworks , a biotechnology company focused on leveraging synthetic ...",
    "url": "https://knowinsiders.com/who-is-shyam-sankar-early-life-career-and-net-worth-41813.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:18.237296+00:00"
  },
  {
    "id": "484241d78806652e",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Palantir CEO’s rant about the Anthropic-Pentagon feud was ...",
    "snippet": "4 days ago ·Although he could have used other language,PalantirCEOAlexKarp’scomments reflected a growing concern over who can dictate the terms of use for AI.",
    "url": "https://fortune.com/2026/03/05/palantir-ceo-alex-karp-anthropic-pentagon-r-word-anthropic-pentagon/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "7d54f02c3d531e46",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Listen to Crowd Gasp When CEO Legend Says What What No One ...Palantir’s Double Conflict of Interest in the War Against IranPlanet Palantir | CountercurrentsPal",
    "snippet": "1 day ago ·Dave Rubin of \"The Rubin Report\" shares a DM clip ofPalantirCEOAlexKarptelling the \"All- In Podcast's\" Chamath Palihapitiya his brutal assessment of why...5 days ago ·AlexKarp,Palantir’s chief executive, has long framed the confrontation as part of a wider inevitability. In an August 2024interviewwith the New York Times,Karpsaid the US would “very likely” face a three-front war against ",
    "url": "https://www.youtube.com/watch?v=PVZJQeZO8VQ",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "9e8dfae70ec5d826",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Palantir’s Double Conflict of Interest in the War Against Iran",
    "snippet": "5 days ago ·AlexKarp,Palantir’s chief executive, has long framed the confrontation as part of a wider inevitability. In an August 2024interviewwith the New York Times,Karpsaid the US would “very likely” face a three-front war against Russia, China and Iran simultaneously – essentially a world war scenario involving the great powers.",
    "url": "https://bylinetimes.com/2026/03/05/palantirs-double-conflict-of-interest-in-the-war-against-iran/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "84fdb0aea8943623",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Planet Palantir | Countercurrents",
    "snippet": "1 day ago ·“I love the idea of getting a drone and having light fentanyl-laced urine spraying on analysts that tried to screw us,” saidAlexKarp, the CEO of the emerging military tech firmPalantir.",
    "url": "https://countercurrents.org/2026/03/planet-palantir/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "d662369f09ea2620",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Palantir CEO Alex Karp Issues Explosive Warning To Silicon Valley",
    "snippet": "3 days ago ·PalantirTechnologies Inc. CEOAlexKarpdid not mince words at a recent industry summit. He told Silicon Valley that trying to gut white-collar employment while also cutting off the military...",
    "url": "https://finance.yahoo.com/news/palantir-ceo-alex-karp-issues-023107210.html?fr=sycsrp_catchall",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "1afdaa9ccd28b143",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Palantir CEO Warns of Nationalization Threat Amid AI Dispute",
    "snippet": "5 days ago ·In a striking address at the a16z American Dynamism Summit in 2024,AlexKarp, CEO ofPalantirTechnologies, expressed his alarm regarding the ongoing tensions between the Pentagon and AI companies, particularly Anthropic and OpenAI.",
    "url": "https://conzit.com/post/palantir-ceo-warns-of-nationalization-threat-amid-ai-disputes",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "8157d0e661570bc3",
    "source": "Web — Palantir Alex Karp interview",
    "source_type": "news",
    "title": "Palantir CEO Alex Karp Issues Explosive Warning To Silicon ...",
    "snippet": "6 days ago ·He told Silicon Valley that trying to gut white-collar employment while also cutting off the military is a fast track to having your technology seized by the government. The remarks were delivered...",
    "url": "https://www.benzinga.com/markets/tech/26/03/51040405/palantir-ceo-alex-karp-issues-explosive-warning-to-silicon-valley",
    "date": "",
    "scraped_at": "2026-03-10T06:04:14.079936+00:00"
  },
  {
    "id": "edfb22410d36b784",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies (PLTR) Revenue 2018-2025 - Stock Analysis",
    "snippet": "5 days ago ·Current and historicalrevenueinformation for Palantir Technologies Inc. (PLTR) stock, including a chart and comparison to related stocks.",
    "url": "https://stockanalysis.com/stocks/pltr/revenue/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "6c5f7e8860f1f5c8",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies Inc (NASDAQGS:PLTR) Revenue",
    "snippet": "2 days ago ·Palantir Technologies Inc's latest twelve monthsrevenueis 4.475 billion. View Palantir Technologies Inc's (NASDAQGS:PLTR)Revenuetrends, charts, and more.",
    "url": "https://www.investing.com/pro/NASDAQGS:PLTR/explorer/total_rev",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "0d07c70167741bcd",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies (PLTR) Earnings Date and Reports 2026",
    "snippet": "4 days ago ·Palantir Technologies updated its first quarter 2026earningsguidance on Monday, February, 2nd. The company issuedrevenueguidance of $1.5 billion-$1.5 billion, compared to the consensus revenue estimate of $1.3 billion.",
    "url": "https://www.marketbeat.com/stocks/NASDAQ/PLTR/earnings/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "844088bf7cd7007f",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Is Palantir Stock Going to $200? - AOL",
    "snippet": "1 day ago ·Palantir'srevenuein the fourth quarter of 2025 increased 70% year over year to $1.4 billion. Itsearningsincreased by almost 80% year over year to $0.25 per share last quarter.",
    "url": "https://www.aol.com/articles/palantir-stock-going-200-002500181.html",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "e9f51a4751d7bd97",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies Inc. (PLTR) Income Statement - Annual ...",
    "snippet": "3 days ago ·Browse annualrevenue, EPS, shares outstanding, and more for Palantir Technologies Inc. (PLTR).",
    "url": "https://fiscal.ai/company/NasdaqGS-PLTR/financials/income-statement/annual/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "d616c7df6ce315cd",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies (PLTR) Annual Net Income - Current ...",
    "snippet": "4 days ago ·Get the annual net income charts forPalantirTechnologies (PLTR). We're 100% free for everything. Get 20 years of historical annual net income charts for PLTR stock and other companies.",
    "url": "https://www.financecharts.com/stocks/PLTR/income-statement/net-income-annual",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "fcf3144781a42b63",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir Technologies Inc. (PLTR:CA) Earnings Dates & Report ...",
    "snippet": "6 days ago ·Palantir Technologies Inc. (PLTR:CA)earningsreport:revenue, EPS, surprise, history, news and analysis.",
    "url": "https://seekingalpha.com/symbol/PLTR:CA/earnings",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "d825980cbe9ecffe",
    "source": "Web — Palantir earnings revenue",
    "source_type": "news",
    "title": "Palantir earnings beat by $0.02, revenue topped estimates By",
    "snippet": "Palantirearningsbeat by $0.02,revenuetopped estimates ...Palantirsees FY 2025revenueof $4.14B-$4.15B versus the analyst consensus of $3.90B.",
    "url": "https://www.investing.com/news/earnings/palantir-earnings-beat-by-002-revenue-topped-estimates-4168757",
    "date": "",
    "scraped_at": "2026-03-10T06:04:09.004722+00:00"
  },
  {
    "id": "fecf076f7d425523",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Palantir's GPT-4-Based AI Can Plan War & Defense",
    "snippet": "Palantir’ s latest offering, thePalantirArtificial Intelligence Platform (AIP), is making inroads into the Pentagon, providing a potential ...",
    "url": "https://www.gizmochina.com/2023/04/27/palantir-ai-war-planning-tactical/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "8675dcc13fc90d06",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Palantir’s AI Powered by GPT-4 Enables Planning of",
    "snippet": "Palantir, a software company that specializes in analyzing, integrating, and presenting vast amounts of data for various industries such as finance, ...",
    "url": "https://www.investmentwatchblog.com/palantirs-ai-powered-by-gpt-4-enables-planning-of-defense-and-war-strategies/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "7478e216d0c29d94",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "UK Govt Signs Billion Dollar AI Military Deal with Palantir",
    "snippet": "AIP,Palantir’s main platform, has been labelled an “ AI kill-chain ” by opponents, alleging “ testing on civilians ” and framing ...",
    "url": "https://expose-news.com/2025/09/21/uk-government-billion-dollar-ai-palantir-military-deal/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "12b3d0d15016c33d",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Palantir Services for Defense | Palantir Partner - PVM",
    "snippet": "From onboarding to use case enablement to ongoing enhancements, PVM providesPalantirservices that helpdefenseteams unlock the power of their data ...",
    "url": "https://www.pvmit.com/markets/palantir-defense-services",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "37bce09e4bf28ff2",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "UK Government Signs Billion Dollar AI Military Deal with",
    "snippet": "AIP,Palantir’s main platform, has been labelled an “ AI kill-chain ” by opponents, alleging “ testing on civilians ” and framingPalantir...",
    "url": "https://ukreloaded.com/uk-government-signs-billion-dollar-ai-military-deal-with-palantir/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "3804293dc4ff392f",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Palantir Designated \"Awardable\" Vendor for Department",
    "snippet": "Palantir’s capabilities, including its AI Platform (AIP) that underpins the solutions available through the Tradewinds Solutions Marketplace , are ...",
    "url": "https://www.nasdaq.com/press-release/palantir-designated-awardable-vendor-for-department-of-defense-chief-digital-and",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "1cbfecc46abb9fee",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Palantir AI Momentum Secures Government Contracts, Protects",
    "snippet": "Palantirleaned hard into generative AI with its Artificial Intelligence Platform, orAIP, and that move is starting to show traction across both ...",
    "url": "https://news.spreely.com/palantir-ai-momentum-secures-government-contracts-protects-taxpayers/",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "17f6af6278d77391",
    "source": "Web — Palantir AIP government defense",
    "source_type": "news",
    "title": "Overview • Security • Palantir",
    "snippet": "...Palantirplatform was built for security-conscious customers who need the capability to handle financial data, Personally Identifiable Information ...",
    "url": "https://www.palantir.com/docs/foundry/security/overview",
    "date": "",
    "scraped_at": "2026-03-10T06:04:01.437150+00:00"
  },
  {
    "id": "7510b6bea1a5168d",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Palantir Secures No-Bid USDA Return-to-Office Contract",
    "snippet": "2 days ago ·Palantirsecured a no-bid USDAcontractin 2025 to deliver a return-to-office tool for employee seat assignments, space utilization, and continuous compliance monitoring. Theawardis tied to a larger $300 million National Farm Securitycontractand comes as the department shed 27,000 employees (a 27% reduction) since September 2024.",
    "url": "https://www.letsdatascience.com/news/palantir-secures-no-bid-usda-return-to-office-contract-a79f79b7",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "960a713002ad6011",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Is Palantir Under Contract to Surveil the Federal Workforce?",
    "snippet": "2 days ago ·Palantirdid not respond to a request for comment, nor did the Department of Agriculture. The newawardis the latest purchase in a larger $300 millioncontractthat the Agriculture Department andPalantirinked last year as part of a sweeping “national farm security” directive with the Pentagon and the Department of Homeland Security.",
    "url": "https://jacobin.com/2026/03/palantir-bossware-workforce-surveillance-tech",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "a59dce7ad64da3e6",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Pentagon AI Ban Puts Palantir Defense Contracts And Valuation ...",
    "snippet": "1 day ago ·The ban forcesPalantirto rapidly rework core AI workflows for US defensecontracts, with potential operational and revenue impact.",
    "url": "https://finance.yahoo.com/news/pentagon-ai-ban-puts-palantir-130711423.html?fr=sycsrp_catchall",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "48a5de6beb330ee3",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "ACTION ALERT: STOP Palantir – MPACUK",
    "snippet": "1 day ago ·Awardeda £240 millioncontracttoPalantirby the Ministry of Defence in December 2025. This was a directawardwithout a competitive tender process. The UK government has also maintained a £330 million, seven-yearcontractforPalantirto build and run the NHS Federated Data Platform, storing sensitive patient data .",
    "url": "https://mpacuk.org/2026/03/09/action-alert-stop-palantir/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "ff5280e327a55734",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Pentagon Anthropic Ban Tests Palantir Defense AI Contracts ...",
    "snippet": "2 days ago ·The restriction introduces immediate operational disruption forPalantir's defense software and touches over US$1b in Defense Departmentcontractslinked to Maven Smart Systems.",
    "url": "https://finance.yahoo.com/news/pentagon-anthropic-ban-tests-palantir-070729995.html?fr=sycsrp_catchall",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "05a62cf2443e8132",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Concerns voiced as Palantir wins £330m NHS data contract",
    "snippet": "5 days ago ·NHS England hasawardedUS IT groupPalantirthecontractto create a new federated data platform (FDP) designed to bring together existing NHS data into a single framework, reigniting debate...",
    "url": "https://pharmaphorum.com/news/concerns-voiced-palantir-wins-ps330m-nhs-data-contract",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "c7a2c72963b53041",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Palantir’s £250m government deal ‘represents a vote of ...",
    "snippet": "5 days ago ·The question comes in light of a £240m deal – effectively acontractextension –awardedto the analytics firm by the Ministry of Defence without any competitive process, owing to what government has said was “an absence of competition for technical reasons”.",
    "url": "https://www.publictechnology.net/2026/03/05/defence-and-security/palantirs-250m-government-deal-represents-a-vote-of-confidence-in-the-uk-minister-says/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "bc1111555305ec66",
    "source": "Web — Palantir contract award",
    "source_type": "news",
    "title": "Palantir to Help Army Optimize Supply Chain Under $85M Contract",
    "snippet": "Palantirearlier received acontractextension valued at $229 million to continue working with the Army Research Laboratory on the experimentation ...",
    "url": "https://executivebiz.com/2022/10/palantir-to-help-army-optimize-supply-chain-under-85m-contract/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:57.686997+00:00"
  },
  {
    "id": "00b688103d8f0aa2",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir rallies 15% for the week as Iran war boosts prospects, muting Anthropic concern",
    "snippet": "3 days ago -Palantir's stock had its best week since August and outperformed all of its large-cap tech peers after the U.S. attacked Iran.",
    "url": "https://www.cnbc.com/2026/03/06/palantir-stock-jumps-15percent-in-week-on-iran-war-boosts-anthropic-muted.html",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "0fa1d0520e9082bd",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir Stock Investors Just Got Fantastic News from Wall Street | The Motley Fool",
    "snippet": "4 days ago -Citi analyst Tyler Radke recently made a splash, maintaining a buy rating and raising his price target on Palantir stock to a Street-high $260.For those keeping score at home, this represents potential gains for investors of 70% compared to ...",
    "url": "https://www.fool.com/investing/2026/03/06/palantir-stock-investors-just-got-fantastic-news-f/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "e388804f3684cfa4",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "US judge blocks former employees from poaching and uses Palantir’s data for AI startup, says: The company would suffer…. - The Times of India",
    "snippet": "13 hours ago -A US judge has ordered three former Palantir Technologies employees to stop recruiting Palantir staff and using its confidential information for their artificial intelligence (AI) startup.",
    "url": "https://timesofindia.indiatimes.com/technology/tech-news/us-judge-blocks-former-employees-from-poaching-and-uses-palantirs-data-for-ai-startup-says-the-company-would-suffer-/articleshow/129345631.cms",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "1dd5d72f092bd4f3",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir Is Back on Wall Street’s Buy List After 38% Plunge",
    "snippet": "1 week ago -The stock, which has long been treated skeptically by analysts due to its extreme valuation, wasupgraded by at least eight firms last month amid a slump that sent Palantir shares down 38% from a record high on Nov. 3 to a Feb. 24 low.",
    "url": "https://finance.yahoo.com/news/palantir-back-wall-street-buy-123242692.html",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "b7446dd77cd6cf7d",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir Stock Up 17% in 1 Month as Iran Tensions Ignite Defense AI Boom",
    "snippet": "16 hours ago -Palantir Technologies (PLTR) stock has surged this past month, climbing almost 17%, surpassing both the overall market and several of its AI peers. The rally has been fueled by heightened defense demand due to the escalating U.S.–Iran conflict.",
    "url": "https://www.barchart.com/story/news/643070/palantir-stock-up-17-in-1-month-as-iran-tensions-ignite-defense-ai-boom",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "0dcf4a41e2f3d2c1",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir faces challenge to remove Anthropic from Pentagon's AI software | Reuters",
    "snippet": "5 days ago -NEW YORK, March 4 (Reuters) -Palantir (PLTR.O), opens new tab is the latest company to face the painful task of unwinding from Anthropic in the wake of the AI lab's dispute with the Pentagon over safety guardrails, raising questions about ...",
    "url": "https://www.reuters.com/technology/palantir-faces-challenge-remove-anthropic-pentagons-ai-software-2026-03-04/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "0c623e7c8ddb9cc4",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Why Palantir Stock Is Surging Today | The Motley Fool",
    "snippet": "5 days ago -Palantir has been posting big artificial intelligence (AI) wins among commercial and government customers, and recent political developments in the tech space could wind up helping the company accelerate public-sector contract growth.",
    "url": "https://www.fool.com/investing/2026/03/04/why-palantir-stock-is-surging-today/",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "1e4a1fa4d8846eb5",
    "source": "Web — Palantir news",
    "source_type": "news",
    "title": "Palantir Is Back on Wall Street’s Buy List After 38% Plunge - Bloomberg",
    "snippet": "1 week ago -Wall Street is about as bullish toward Palantir Technologies Inc. as it’s ever been, as the potential for growth in the company’s defense business brings enthusiasm back to the stock following a four-month selloff.",
    "url": "https://www.bloomberg.com/news/articles/2026-03-03/palantir-is-back-on-wall-street-s-buy-list-after-a-38-plunge",
    "date": "",
    "scraped_at": "2026-03-10T06:03:50.689753+00:00"
  },
  {
    "id": "fb0e5adc6f4b12c1",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "USDA needs Palantir to tell workers where to sit - theregister.com",
    "snippet": "USDA needs Palantir to tell workers where to sit &nbsp;&nbsp; theregister.com",
    "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTFA5bms4US0wd0ZSejBSNkhHWXUtN0tXemZvSnhmTHAybnpvdGRnQ3JFdnRUNFZXNHFVejdSTldzX0JfUTZaZUlKRk11cS1TdXh4ZGVmcWtuWV9JbzY2bmVVcEE4NUt3TXhnc2ZwWnk1TDByQ1NVa0hHSTZ3?oc=5",
    "date": "2026-03-10",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "e653241781f8f7b4",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir stock price ended at $156.43 on Monday, after losing 0.464% - StockInvest.us",
    "snippet": "Palantir stock price ended at $156.43 on Monday, after losing 0.464% &nbsp;&nbsp; StockInvest.us",
    "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxNUWVRVzdPdExkeEJvdzJ6M1NfVldaVUEwMXU4aS1vVnBoOWowUkpjZTk5aXd3RHhsdG53ZjcwaG14NDJRRHRfcWk2aUhfa2xqNFAxWE9Dek1zRXhBVnlNWFlkSkRlZGtkdTdROGhvdnRFSm5iUmg3Q1M2YjBsT0YydGFiSC1fOGpWYlRoSS1mX0xzY1ZPVllRbWFVOExVVjAzcy1hblo4QW5iNm9M?oc=5",
    "date": "2026-03-10",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "8cd3f7e9007d44e7",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Nvidia, Palantir And How To Invest In The Volatile Fog Of War - Investor's Business Daily",
    "snippet": "Nvidia, Palantir And How To Invest In The Volatile Fog Of War &nbsp;&nbsp; Investor's Business Daily",
    "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxNdVhhSTJtU0k4SUhQZlplNDUtbnpOUGhaQnRPSUhHUWlWTzhMYTM0aFo0WGhWUmRqTllkcU0wdm5tM1JZTFQ2Ykh5Smt2N3c0bHAzUjBkMlJDTWw1WDMtLVNUeXA2VmhEbzd2N005ZnZMOC0zdWNZMWI0bGJGQmljREFaWUktYXIycmZyYWdTZ3hMTFVURlRGZ3JUaE1admMtaHlvV29yUHhGWnBIRVlVZnR0U1FseFU?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "6094a85a7ddcad9e",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir Confronts Claude Ban As Valuation And Momentum Diverge - Yahoo Finance",
    "snippet": "Palantir Confronts Claude Ban As Valuation And Momentum Diverge &nbsp;&nbsp; Yahoo Finance",
    "url": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOVTY0U2F6M2s0X0dvNkhXc1JvcW9ITEJRNHEwdFRNbTNTOUQwM2Vrc0t2R0k4SjE4RER3WHJpQWRFcFBkMXRHY0NkOXpNYnZKcmFFNWw0Z1dfYzZWOTZYU2tyeEF0OEZPNWhxUEg5Mm15ZVJJa2dibkkzSUNCeks4azBPNFBydWo4ZnpTZlF3?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "d0f9a0c27aa2351d",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "A Clique of Unhinged Techno-Optimists Is Putting Humanity at Risk - Informed Comment",
    "snippet": "A Clique of Unhinged Techno-Optimists Is Putting Humanity at Risk &nbsp;&nbsp; Informed Comment",
    "url": "https://news.google.com/rss/articles/CBMic0FVX3lxTFBfNXk4blJSdHFnX0RJYXNJdmJVRHItR2MtODRzbzJXSk5YVmFHYTdscnZUSVk5MWQ3YlFndHVXYV9WV29rNURXM3BvY3hLV1FTVUFRSmRIMmtvVWFqdU1kRFpxVUFMeWw0UzdGcGdQLUJqNUE?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "0a909b533837855e",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Why Palantir Is Soaring While Big Tech Tanks - Benzinga",
    "snippet": "Why Palantir Is Soaring While Big Tech Tanks &nbsp;&nbsp; Benzinga",
    "url": "https://news.google.com/rss/articles/CBMingFBVV95cUxQQ0t4d3NTcUVsLW81MUxPa2xud0s4ZjVfVjRoVnVZMnoydDlWN1psblR5YWpHUUd1OW9SaEFuc3hkTTNPLXQ5S2k4clEzRVFwdzlXcnRHUFppNXNFSVhlUjE0YU00bXRhUFpLdFdUZVQwc29iOWhpaTZsUEFVR05yMFJ5c0lsVVhCc1FvZWhzVGJoUkxpYnZURHEzRUVIdw?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "5db3e67a29a48288",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Prediction: This Is How Much Further Palantir Stock Could Fall in 2026 - The Motley Fool",
    "snippet": "Prediction: This Is How Much Further Palantir Stock Could Fall in 2026 &nbsp;&nbsp; The Motley Fool",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxQTlFGM0RWWnpZc3BSM2YtZGJ4cjRIdjZzdjJ1Z05xT1NuR0xvLU85Ry1ENFMyTnl2SDVzOUJUT05nZHZvUGdGTVRRWURzaXNZRDNELUZYSE1QdUNheC1ZdHR6UnBrdmFTOUdXRHFGQzlzZllkMndfdmFBM0JRTU9aNUNLTGxVUzNtM3VJN2lHQkpDdWdvRms5dQ?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "10d0f80cfe27a54e",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Planet Palantir - LA Progressive",
    "snippet": "Planet Palantir &nbsp;&nbsp; LA Progressive",
    "url": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE9acnhnQy1WSS0wcjR1X2t2dWZLLUtybXpNREx6U0JQNUlnWEZ5QnUyMVd3dU5ocXR0ZW82d21JX0xGSVRmRXhuYUdYNmZXR29CcHZuZGx4SXlyRkdISzN6a1A3X29EcHJE?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "ae1ed9b61ff8605d",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Letter to the Editor: Auchincloss should give Palantir donations away - newtonbeacon.org",
    "snippet": "Letter to the Editor: Auchincloss should give Palantir donations away &nbsp;&nbsp; newtonbeacon.org",
    "url": "https://news.google.com/rss/articles/CBMinwFBVV95cUxNb2ZOX2tjRXFxYmRtUmIzS0N0eEstaU9XeVR5c1ZEUWZGbnotNGhuamxqVXlwaksycks4enhZNFNGa2F4YUxmZzdZMXhOd3l4RlI0Ykw2R3ZjbWczeUNoOUJEVzBxdFpwVDVsdnkwTTAtTVhZMW1XS3RQNDVsemFMR0J0bkczRG9PLTY3OTN1dkdzZ3NFd1NnVzlaQmItWlU?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "0cf9820e5f3120b0",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Why Analysts Are Bullish on Palantir Technologies Inc. (PLTR) - Finviz",
    "snippet": "Why Analysts Are Bullish on Palantir Technologies Inc. (PLTR) &nbsp;&nbsp; Finviz",
    "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxQVDRhRTJVSzJLSW1CdFMwMGNNdXFMT0UwT2RKaU81WkJPTklYVUNnWlc2eFl1OXNrdzdRZDdtRjhvRVN0bC1ROWd6NFBrVTlLZFBEVC1ORy1Qem5YTl9EVzFoazlSZHkzNFEwMDlPS3dFblBGd1dtQUZyNm9GRkVuTEhESXgwMWhTU01VTTM5TWhwZTg?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "6d74b27f261e3b63",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir Surges as Geopolitical Tensions Reshape Defense Demand - TradingView",
    "snippet": "Palantir Surges as Geopolitical Tensions Reshape Defense Demand &nbsp;&nbsp; TradingView",
    "url": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxPR3pxMmx4eUt6UkdOQUVHdUhhMlVoSE91TTVqQUdWSThaV0hKa0xGNm1jY0VKbEoxUXh6MVZ1Y0t6NG82d2FtdjZOdDdfQU9HUHdNX1BTQTRmNUR0WmRhM255THhpMjQzYnRBUGRUbTZpaVo4TktqMzREeXpoek1ma0tBaXZZTld1a0lVTzNINFFILUVYRlJSMmVWYkFNS2JRWnpSNW1Mb2Rpb3Bmb3dXcG9ILTd0R0xxcEo4WV9kMFU?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "f1db9ef8ca545796",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir Stock Up 17% in 1 Month as Iran Tensions Ignite Defense AI Boom - Barchart.com",
    "snippet": "Palantir Stock Up 17% in 1 Month as Iran Tensions Ignite Defense AI Boom &nbsp;&nbsp; Barchart.com",
    "url": "https://news.google.com/rss/articles/CBMitAFBVV95cUxQVHFJMmE5YnhoNE1pdGRCbXdsVTlNWDhpUXBnQ2RPOHpqaHptRklqb0hpdTl5S2p1VUV5bm1ocGtHbVhjUFBOWlFOM2JrZ0RBaWYwdU5wTkJ1NUlUSXhSZzdVaEZ1eGFJaUhKN3Z5NzhVYlM5a1NJaXhJaEgzWE0wWUVvLWhPWHBRSmVUNjJsMnhkNkkyZEtYdVIyT1o2ejV6WVQwQnV2SlE0TnpoczVNTHc1TWc?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "d6c9db31fe0c617e",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir sees best week since August as Iran war 'bodes well' for contract pipeline - Seeking Alpha",
    "snippet": "Palantir sees best week since August as Iran war 'bodes well' for contract pipeline &nbsp;&nbsp; Seeking Alpha",
    "url": "https://news.google.com/rss/articles/CBMiuwFBVV95cUxOYXhPTWxRMlRBSzVCQnk5Zl9iVjBKUnl1U2hLaGV2UEdlaHlTeVJ4Q0tNcTk2UHNUVy02elpBSnlFNHhKeThYanlid2MwU1dleDZSNEZrYjE3UkpFWlZGY3ZpcU9hQkg0ZGRIWFd3eUtJbmthUVkzc2hNeGN6Tlh6REp4alpWWWpxOE1ZU25QbDMzVWFHZjE0T3JIbTNTV2NMWEJFckZ4T2pBazZFVndyWU45VTFVeHlnUEN3?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "9badc26824959b17",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Is Palantir Stock Going to $200? - Nasdaq",
    "snippet": "Is Palantir Stock Going to $200? &nbsp;&nbsp; Nasdaq",
    "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE5aWTZPNGxDNXZkcDFMZWRNS3pRajc5Zi1vb0c4ODhBNUJ0SFhRMUFHdTZuMXluTXRpbzh0OHlXWFpMeUlEcTFqZkl5cHo4aEhSUnowTTlZVldab2ZJak9OSVFPRW1BTWs?oc=5",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "61f22fbbb09cdd55",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Daily Thread - Monday Discussion! Let's talk about the good, the bad, and all things Palantir & PLTR! 💎🤲🏻",
    "snippet": "The thread for all your speculating, socializing, philosophizing, hypothesizing, and melodramatizing! Want a flair? Message the mods with proof of the following, making sure to remove any personal information: OG Member &amp; Holder - a link to your comment/post in r/PLTR from 2020 or 2021 Early Investor - a screenshot of your PLTR share purchase from 2020 Whale - a screenshot proving that you own",
    "url": "https://www.reddit.com/r/PLTR/comments/1rot8uc/daily_thread_monday_discussion_lets_talk_about/",
    "date": "2026-03-09",
    "scraped_at": "2026-03-10T06:03:43.499577+00:00"
  },
  {
    "id": "46b60dff81c85ebf",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Is Palantir Under Contract to Surveil the Federal Workforce? - Jacobin",
    "snippet": "Is Palantir Under Contract to Surveil the Federal Workforce? &nbsp;&nbsp; Jacobin",
    "url": "https://news.google.com/rss/articles/CBMifkFVX3lxTE5oTlpCV2V1ZUVwZ2FBZlF5c29NQU5tRkZoUXFZcGdRZngzTXN3QWJZU05WSHJncmd3VHNucjM0ekFVWXpBbVF5eTNmOVF4dzlrNGxWeS1LZU5GNHR2MXpfeWkweEpWWHo4c29CcXVjNWZQaVNqMXdSY2xDT3pTUQ?oc=5",
    "date": "2026-03-08",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "35ddd34263a49e35",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "What Is Going on With Palantir Stock Right Now? - Yahoo Finance",
    "snippet": "What Is Going on With Palantir Stock Right Now? &nbsp;&nbsp; Yahoo Finance Palantir: The Rebound Is Just Beginning (NASDAQ:PLTR) &nbsp;&nbsp; Seeking Alpha Palantir Stock Catapults 9% Higher as War Tech Demand Surges &nbsp;&nbsp; TipRanks",
    "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTE5JM2c3SlJiTTh0ZWVrcDdWaE1ZWWk1YnNWSVhFSnpFMWdad2ZLb1RnY3RfMUZZa3NhUEx6TmhsZnhqR3d3VGp6NWNKWF81LUFzZllCTHlLV1AzYXB2TEN2dTNKTjFOYzJNeG8tbUdoRUwxM1FCbUhJM1Rn?oc=5",
    "date": "2026-03-08",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "90d95d8917a6cb55",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "2 Artificial Intelligence (AI) Stocks to Sell Before They Fall 40% and 55%, According to Wall Street Analysts - The Motley Fool",
    "snippet": "2 Artificial Intelligence (AI) Stocks to Sell Before They Fall 40% and 55%, According to Wall Street Analysts &nbsp;&nbsp; The Motley Fool",
    "url": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPanMwLUJxTlI3R0ZQNnAtWG5jS3ItZFZWQlFSWUktdUVlM1hZd1RBdUxoUzV2YmpBTU00TGFyeFBtM2FuM3M1UzU0cFN0ejltNl9BNFZMNFQ0NEJxdVVWUVRJY3dGZG5QMlh0OVZDT24xUWxsV1NkUUN5cVpDRUtXWDROSno0MDZKbnVTeU9rV09scDVhckE?oc=5",
    "date": "2026-03-08",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "f5770d5752986df7",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Pentagon official recalls 'whoa moment' when defense leaders realized how much they need Anthropic - Fortune",
    "snippet": "Pentagon official recalls 'whoa moment' when defense leaders realized how much they need Anthropic &nbsp;&nbsp; Fortune",
    "url": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQN3haUnlhMGR4eGhndGZXSXZLUHUxY19PLWhpY3k4OGFKWjBDVHVvbEhFNXFGVGlRdk5fS2F6amlsM0N0S1lwSkJqZS1nN0haby1oN29LemtLNU1uTzdUZkFGRE5BeFVDLW1JNGpXLUpMMzFMNWpNZ2JBcVJzd3hVVmFaU2JCaXlEWnFCSmRHYTltclZ1bXJ5R0R6MFJOTHNWRW5rTjVUYS1Ydw?oc=5",
    "date": "2026-03-07",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "b5d80c9484f6d2c5",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Anthropic Deemed a ‘National Security Threat’ — Is Palantir Technologies At Risk? - 24/7 Wall St.",
    "snippet": "Anthropic Deemed a ‘National Security Threat’ — Is Palantir Technologies At Risk? &nbsp;&nbsp; 24/7 Wall St.",
    "url": "https://news.google.com/rss/articles/CBMivAFBVV95cUxPTmRUQXA5b3N3anBqa2ZFcnQyN0M5dC1kdHhBcmJWd2JmWU41V1FCYnR2OUVjV3k0NThlQVg4SGpxWGg3RXhJbEhIMW05MTg0Z1FDRlozdzdQTjRWTkdlSnFCX0RnT1owd1hoVDVPMDRabENYeXhTTTZpdGNKWmZYT3hNMDlDQUtlRXFGejFDd00yb2hkUHhmNnJ0RDJIbUNzVEV4dE1FSUhob1dPQTJweHN1TzlrMGRqSmhPWQ?oc=5",
    "date": "2026-03-07",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "46f3ed9a8f71a9c5",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir CEO Alex Karp Issues Explosive Warning To Silicon Valley - Yahoo Finance",
    "snippet": "Palantir CEO Alex Karp Issues Explosive Warning To Silicon Valley &nbsp;&nbsp; Yahoo Finance",
    "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPeVJuVTdjREx6XzQ2eThvYmpUX0hVTlJKYjFLZDc1SzY3QU51akZsSFhydG54SFFMSVpkR212cmlEVzhhVkZMektPVEtCbXVub3hPQVJTNVctZm1VdVQtZXhSMjVPUml3Y1hIUzExV0U4bXhQUXlqTUNyQ0NvOUtfbg?oc=5",
    "date": "2026-03-07",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "a971ca0ed38d1d52",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Weekend Discussion Thread! Palantir, PLTR & Chill 😎",
    "snippet": "Anything goes in this thread. You can talk about Palantir. You can contribute some DD about other stocks. You can shoot the breeze about random topics. Only rule is to follow the reddit user rules and be a respectable human. See you on Monday! &#32; submitted by &#32; /u/AutoModerator [link] &#32; [comments]",
    "url": "https://www.reddit.com/r/PLTR/comments/1rn4apc/weekend_discussion_thread_palantir_pltr_chill/",
    "date": "2026-03-07",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "1d95376898821fff",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir rallies 15% for the week as Iran war boosts prospects, muting Anthropic concern - CNBC",
    "snippet": "Palantir rallies 15% for the week as Iran war boosts prospects, muting Anthropic concern &nbsp;&nbsp; CNBC",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNRHpyWHVvMWlHRlRrV2ZwYk9NOEdwaEN3UU1jTmtBWnpoTEctT2tUUW9EOVJyV0xQa01fSWhkWjJqemZSUFpJUmo2QjY4LWs4a0RqanNJNk1XSmZDQVBiSEVnX0xiaGs0R2RzbUQ5RFBwam9MTFF4eUFhaWVmd2NrbWN3dDdiZUhnakhTZXpDV0NkMXlhRERoSnQ0QjB3d2NLVUtvODhiUjhTbnRrRXc40gG0AUFVX3lxTE1UTXZIaUpjcGY2ZDRyQTRsT05GTGhtSzd6V0RkNlRUejViN0Z3VjBFM0l4YnJfWkNzbGVlMjRYT0tBd0ZNTjNLYkNwRGpqUGljMkYzQXpKQnlNRzRYUlptRnNPZGlGS0pXOWFINzAzOHRPTV90NU1WYjh0TjRHMGhwa0ZPeVRkaHAydE1HaS01Q2xhczhoejNFVjVfNTIyZDFtRXBaS05kZGt6TzNmZEYxSUtfUg?oc=5",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "333964ff9023c789",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Ex-Palantir AI Workers Blocked From Poaching, Using Secrets - Bloomberg.com",
    "snippet": "Ex-Palantir AI Workers Blocked From Poaching, Using Secrets &nbsp;&nbsp; Bloomberg.com",
    "url": "https://news.google.com/rss/articles/CBMirgFBVV95cUxPQ1dXMkh4Qzh1R2hHeUtreDdiZm5xM1ZmR3V4NVhrUjE0UWdwTFdlc3dyWGJLbUw3OGZoZEdUSkNsb2Nhb3B0TXV4bDhTVmpZVW5ZQTNYZmdBUGhYc2ZZNnFRX2VWblRFNjVsdnNUTEx3aTFPc3FoM1VRUHBPemlRaFJJcERIWUw2RW5lV1ZhMGhWMzk5YndjU2pHcjFDdDNnb2Y3RUc0NXF6SjBnQVE?oc=5",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "3a515311dcd6eca2",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "New Palantir Price Target After Pentagon Change Threatens Shakeup - TheStreet Pro",
    "snippet": "New Palantir Price Target After Pentagon Change Threatens Shakeup &nbsp;&nbsp; TheStreet Pro",
    "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxPOWJ2QUlxVEdEMUVCX0U4UFdtRzBwOGs5MzktNDdFNzRqN2kxNWhCbEpLT21LRjB1a1lIbFo3RUlCYlFXbXZvUHNGRC1Vdjl4R0tKSXdlcmhHbzRSaGNkVm8zSW1mZUt5NWs1SGg2Smx1WHpiSXNXczBCR1ZLcE94czBqdTdGWXhrMXY5d19CZzN1d01yVGtsSzJyc0hTRkNiN05mTjdB?oc=5",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "b1744abc2fee20f4",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir Stock Investors Just Got Fantastic News from Wall Street - The Motley Fool",
    "snippet": "Palantir Stock Investors Just Got Fantastic News from Wall Street &nbsp;&nbsp; The Motley Fool",
    "url": "https://news.google.com/rss/articles/CBMimAFBVV95cUxNMGdERTJWMk9ybkhCeFkwcWF0TW0wSkFUQXZGRmV2Y3pxaVBqUWMxeHlvS0ZaYzBRT0NpYlhrNEVidzU3ekhKNWE1VmR5UnYydF9qbGp6a3l1SVJJWHNTN3U3eEc0ZE5JalBrQ2RlTVozNUJHUjdJNGpCeGkzdWpVN2JPY0hiaVVCaVRBakR1TG9TTWV4UWFNVw?oc=5",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "559cf6f89437d4dc",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Peter Thiel Sells Palantir; He May Regret It - Seeking Alpha",
    "snippet": "Peter Thiel Sells Palantir; He May Regret It &nbsp;&nbsp; Seeking Alpha",
    "url": "https://news.google.com/rss/articles/CBMijAFBVV95cUxOWmRJNzVSaWVuaTRPWHFuaktzbDRINGpTYWNQaVQxVEc1ZTloSVlBVHZ5LTFKTWJZTktPRll4QmpuNFBhSmJFeG8yWVl1bVJlYkNvd25UTVA2TDFoMlBkTnktdGNYckllbHdtWnAxRFo3dmtXR1B6cjF1RnRjRkk5cHFKNWxZVy1udGpnVg?oc=5",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "75e17d78a694f22d",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Daily Thread - Friday Discussion! Let's talk about the good, the bad, and all things Palantir & PLTR! 💎🤲🏻",
    "snippet": "The thread for all your speculating, socializing, philosophizing, hypothesizing, and melodramatizing! Want a flair? Message the mods with proof of the following, making sure to remove any personal information: OG Member &amp; Holder - a link to your comment/post in r/PLTR from 2020 or 2021 Early Investor - a screenshot of your PLTR share purchase from 2020 Whale - a screenshot proving that you own",
    "url": "https://www.reddit.com/r/PLTR/comments/1rm81it/daily_thread_friday_discussion_lets_talk_about/",
    "date": "2026-03-06",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "65d4441e413b9716",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir CEO’s rant about the Anthropic-Pentagon feud threatening his company was about a lot more than a dirty word - Fortune",
    "snippet": "Palantir CEO’s rant about the Anthropic-Pentagon feud threatening his company was about a lot more than a dirty word &nbsp;&nbsp; Fortune",
    "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxNX2xMcWs4Y3BjQ1dDSXBoLVc4MUd1SFlfUnlyVG1IVnR2WmZHM3BsRkh0TE50TENlckpLNXg4eG1lNDRkQy1qY1BRUkZFNW5DRnpxX1dwMDJxNk5BckVOa19BWXJsT0Y3T09xOHNrd1M2dm5CWS02a3hfVGI4dlBmd0kyNjhiWkxWYjc4aTFqZjhKbnFLWjRKUzd1QkxiTENm?oc=5",
    "date": "2026-03-05",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "d8e4e4e520ddaea3",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "🗿",
    "snippet": "&#32; submitted by &#32; /u/JackPrescottX [link] &#32; [comments]",
    "url": "https://www.reddit.com/r/PLTR/comments/1rllf4n/_/",
    "date": "2026-03-05",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "8c5529381c35f08d",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "George Noble is short PLTR?",
    "snippet": "George Noble posted some FUD today on PLTR. My guess, he’s short and needed to buy back shares. &#32; submitted by &#32; /u/Lawrence_Thorne [link] &#32; [comments]",
    "url": "https://www.reddit.com/r/PLTR/comments/1rlofkn/george_noble_is_short_pltr/",
    "date": "2026-03-05",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "3c761ec6b5056092",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Daily Thread - Thursday Discussion! Let's talk about the good, the bad, and all things Palantir & PLTR! 💎🤲🏻",
    "snippet": "The thread for all your speculating, socializing, philosophizing, hypothesizing, and melodramatizing! Want a flair? Message the mods with proof of the following, making sure to remove any personal information: OG Member &amp; Holder - a link to your comment/post in r/PLTR from 2020 or 2021 Early Investor - a screenshot of your PLTR share purchase from 2020 Whale - a screenshot proving that you own",
    "url": "https://www.reddit.com/r/PLTR/comments/1rlbsib/daily_thread_thursday_discussion_lets_talk_about/",
    "date": "2026-03-05",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "4c8d587e97c4c9e6",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Is Palantir Stock Entering A New Growth Phase? - Forbes",
    "snippet": "Is Palantir Stock Entering A New Growth Phase? &nbsp;&nbsp; Forbes",
    "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxQU0h0T3dISlRPWGNCeTlRSVpBcGVXdlBfeEhwNmM5UDJnV3U1QW5QbzZJZU4zMklwU2wzdUwyRUw5YXFsNlQzbGJkVUxzRGtmeldNM0dORFM3bjMySEstNG1CNnpGNUV0V3VsY1MtOS1pLUt4R01nUXdrZWtKUzNqZ2Z6aHpFSDRQR2ZnanZVa2JBWkRENmpXQ1Fxd1pjVm4yeWI3d1ZUcw?oc=5",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "e2987d012da0220c",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir Stock Technical Ratings Improve Amid Defense Sector Rally - Investor's Business Daily",
    "snippet": "Palantir Stock Technical Ratings Improve Amid Defense Sector Rally &nbsp;&nbsp; Investor's Business Daily",
    "url": "https://news.google.com/rss/articles/CBMimwFBVV95cUxNMUZScm1XLWpqRTZ3bHVHTFZlQmJaTHBMNmRyU0ZZSTVzSmFHQjdRRjFOT0s1cktVQ0hXWU5HSzNCbkgwVEFCSHRqMkoyUEl3Q3Y5THRHc0Jnd1lDQkg5Zi1KMUlqNVJ1X2VwYlNzLWhJRkFzUTNLblR6U3RVM0xZQUtFS1hGV0tGQU5TWFZNX2Zma1p0UUcydEpjUQ?oc=5",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "11ddb11186e199ee",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Why Palantir Stock Is Surging Today - The Motley Fool",
    "snippet": "Why Palantir Stock Is Surging Today &nbsp;&nbsp; The Motley Fool",
    "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOa0ZBRVA2RHV3QVpjX0JVaXQtdWQyZzVFUldHcWJ5TFdtRlpHUnRTc0dzc1Z3aFdjLUlwX0tjdGNHdThxYmxCRXA2UEU1eGNRVUstcVFmLU56ODNhNjlqZURIb1JMbWQ4TmlhbEpiM0doS0FFNF9sYk91VnFOaWRxX1pnSjc?oc=5",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "ecc7190c384f3c61",
    "source": "Google News — Palantir",
    "source_type": "news",
    "title": "Palantir faces challenge to remove Anthropic from Pentagon's AI software - Reuters",
    "snippet": "Palantir faces challenge to remove Anthropic from Pentagon's AI software &nbsp;&nbsp; Reuters",
    "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNa3dDNXpjRm5qN3RjMC1YWTFzdzU1RXl4SnhBa0w5ZUk4QllUcmY3TnZCWDRSdGNxSy1MZFAyMnh6eHltLUtXNU1FYzFIeTVSMHV4dm5rWkhtcXVnX1FKNEZMZFNONmZOcFhMWFVoY0xOZlJGdVFzNk5XT2xQV1RLQ2ZQUVo2UUpiaUxZb0dMZTlXR3BXbUJWcnpFNHdDWk1XNDh2azloTHNSSlF5RVVr?oc=5",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:31.921470+00:00"
  },
  {
    "id": "659cd3c014e16916",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Daily Thread - Wednesday Discussion! Let's talk about the good, the bad, and all things Palantir & PLTR! 💎🤲🏻",
    "snippet": "The thread for all your speculating, socializing, philosophizing, hypothesizing, and melodramatizing! Want a flair? Message the mods with proof of the following, making sure to remove any personal information: OG Member &amp; Holder - a link to your comment/post in r/PLTR from 2020 or 2021 Early Investor - a screenshot of your PLTR share purchase from 2020 Whale - a screenshot proving that you own",
    "url": "https://www.reddit.com/r/PLTR/comments/1rkfnqh/daily_thread_wednesday_discussion_lets_talk_about/",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "902622f9644674c9",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Peter Thiel sells 2mil shares, thoughts?",
    "snippet": "&#32; submitted by &#32; /u/moon_recon [link] &#32; [comments]",
    "url": "https://www.reddit.com/r/PLTR/comments/1rkq24d/peter_thiel_sells_2mil_shares_thoughts/",
    "date": "2026-03-04",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "7ab00e7fb854bf96",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Iran war heralds era of AI-powered bombing quicker than ‘speed of thought’ | AI (artificial intelligence)",
    "snippet": "&#32; submitted by &#32; /u/Equivalent_Horror628 [link] &#32; [comments]",
    "url": "https://www.reddit.com/r/PLTR/comments/1rjj6n9/iran_war_heralds_era_of_aipowered_bombing_quicker/",
    "date": "2026-03-03",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  },
  {
    "id": "084f4b5b0ba3ada3",
    "source": "r/PLTR",
    "source_type": "blog",
    "title": "Daily Thread - Tuesday Discussion! Let's talk about the good, the bad, and all things Palantir & PLTR! 💎🤲🏻",
    "snippet": "The thread for all your speculating, socializing, philosophizing, hypothesizing, and melodramatizing! Want a flair? Message the mods with proof of the following, making sure to remove any personal information: OG Member &amp; Holder - a link to your comment/post in r/PLTR from 2020 or 2021 Early Investor - a screenshot of your PLTR share purchase from 2020 Whale - a screenshot proving that you own",
    "url": "https://www.reddit.com/r/PLTR/comments/1rjjjvq/daily_thread_tuesday_discussion_lets_talk_about/",
    "date": "2026-03-03",
    "scraped_at": "2026-03-10T06:03:43.500791+00:00"
  }
];
