// ===== SOURCES CONFIGURATION — DAILY INTELLIGENCE FEED =====
// All sources the scraper pulls from. Loaded by the dashboard to show the Sources panel in the Inbox tab.
// Scraper runs daily at 08:00 UTC via GitHub Actions.

window.SOURCES_CONFIG = {

  x_accounts: [
    // === OFFICIAL / PALANTIR ===
    { handle: "PalantirTech",       tier: 1, category: "official",       platform: "X",
      description: "Official Palantir Technologies company account. Contract announcements, product launches, and executive commentary.",
      focus: "All Palantir news", palantir_specific: true },
    { handle: "FirstBreakfast",     tier: 1, category: "analyst",        platform: "X",
      description: "First Breakfast publication account — Palantir-focused essays and commentary by Shyam Sankar, Madeline Hart, Greg Little, and Blake Seitz.",
      focus: "Palantir strategy & culture", palantir_specific: true },

    // === LEADERSHIP ===
    { handle: "ssankar",            tier: 1, category: "leadership",     platform: "X",
      description: "Shyam Sankar — CTO of Palantir Technologies. Strategic essays on AI, defense, and software eating the state.",
      focus: "Palantir strategy / AI policy", palantir_specific: true },
    { handle: "traestephens",       tier: 1, category: "leadership",     platform: "X",
      description: "Trae Stephens — Palantir co-founder, Founders Fund partner, and Anduril board member. Defense tech investment and policy.",
      focus: "Defense tech / national security", palantir_specific: true },
    { handle: "JTLonsdale",         tier: 1, category: "leadership",     platform: "X",
      description: "Joe Lonsdale — Palantir co-founder, 8VC founder. Views on tech policy, defense, and building enterprise software.",
      focus: "Defense tech / venture capital", palantir_specific: true },

    // === PALANTIR STAFF — FIRST BREAKFAST ===
    { handle: "Madeline_Zimm",      tier: 2, category: "analyst",        platform: "X",
      description: "Madeline Hart — Palantir Defense team. Author at First Breakfast and Kinetic Reviews. Writes on AI in national security.",
      focus: "Defense AI / First Breakfast", palantir_specific: true },
    { handle: "BlakeSeitz",         tier: 2, category: "analyst",        platform: "X",
      description: "Blake Seitz — Content Strategist at Palantir. Author at First Breakfast. Government software and AI commentary.",
      focus: "Palantir content / First Breakfast", palantir_specific: true },

    // === COMMUNITY / ANALYSTS ===
    { handle: "PLTRs_Palantir",     tier: 2, category: "community",      platform: "X",
      description: "Leading community account aggregating Palantir news, contract wins, analyst commentary, and investor discussion.",
      focus: "All Palantir news (aggregator)", palantir_specific: true },
    { handle: "amitisinvesting",    tier: 2, category: "analyst",        platform: "X",
      description: "Amit Kukreja — PLTR-focused investor and newsletter author (amitsdeepdives.substack.com). Deep dives on contracts and financials.",
      focus: "Palantir investment analysis", palantir_specific: true },
    { handle: "arny_trezzi",        tier: 2, category: "analyst",        platform: "X",
      description: "Arny Trezzi — Palantir investor and newsletter author. European perspective on PLTR strategy and deal flow.",
      focus: "Palantir investment analysis", palantir_specific: true },
    { handle: "dsmiley411",         tier: 2, category: "analyst",        platform: "X",
      description: "Defense and government tech analyst. Long-form takes on Palantir contract wins, DoD IT modernization, and federal AI.",
      focus: "Defense tech / PLTR contracts", palantir_specific: false },
    { handle: "muddywatersre",      tier: 2, category: "analyst",        platform: "X",
      description: "Muddy Waters Research — prominent short-seller. Bearish perspectives and investigative research included for balance.",
      focus: "Short-seller / skeptic perspective", palantir_specific: false },
    { handle: "chamath",            tier: 2, category: "investor",       platform: "X",
      description: "Chamath Palihapitiya — Social Capital founder, prominent tech investor. Commentary on defense tech, AI, and government software.",
      focus: "Tech investment / AI policy", palantir_specific: false },
    { handle: "NSheinbaum",         tier: 2, category: "defense_media",  platform: "X",
      description: "Noah Sheinbaum — Host of Crossing the Valley podcast (frontdoordefense.substack.com). Lessons for startups entering defense.",
      focus: "Defense tech / podcast", palantir_specific: false },

    // === DEFENSE MEDIA ===
    { handle: "BreakingDefense",    tier: 1, category: "defense_media",  platform: "X",
      description: "Breaking Defense — premier defense industry trade publication. Contract awards, program updates, Pentagon policy.",
      focus: "Defense contracts & policy", palantir_specific: false },
    { handle: "DefenseOne",         tier: 1, category: "defense_media",  platform: "X",
      description: "Defense One — national security news covering Pentagon, intelligence community, and defense technology.",
      focus: "National security / defense policy", palantir_specific: false },
    { handle: "C4ISRNET",           tier: 1, category: "defense_media",  platform: "X",
      description: "C4ISRNET — command, control, communications, computers, intelligence, surveillance & reconnaissance technology news.",
      focus: "Military tech / C2 / ISR", palantir_specific: false },
    { handle: "defense_news",       tier: 1, category: "defense_media",  platform: "X",
      description: "Defense News — global defense industry coverage including procurement, programs, and international defense contracts.",
      focus: "Global defense industry", palantir_specific: false },

    // === FEDERAL TECH MEDIA ===
    { handle: "FedScoop",           tier: 1, category: "media",          platform: "X",
      description: "FedScoop — federal technology policy, procurement, and digital government news. Covers CIO/CISO community.",
      focus: "Federal IT / govtech", palantir_specific: false },
    { handle: "NextgovFCW",         tier: 1, category: "media",          platform: "X",
      description: "Nextgov/FCW — federal IT procurement, contracting, and digital modernization. Merged publication covering all civilian agency tech.",
      focus: "Federal IT procurement", palantir_specific: false },
    { handle: "GovConWire",         tier: 1, category: "media",          platform: "X",
      description: "GovConWire — government contracting news, IDIQ awards, and prime contractor activity across all agencies.",
      focus: "Government contracting", palantir_specific: false },

    // === POLICY / THINK TANKS ===
    { handle: "HillValleyForum",    tier: 1, category: "defense_policy", platform: "X",
      description: "Hill & Valley Forum — bridging Silicon Valley and Capitol Hill on national security and defense technology policy.",
      focus: "Defense tech policy / DC-Silicon Valley", palantir_specific: false },
    { handle: "CSETGeorgetown",     tier: 2, category: "policy",         platform: "X",
      description: "Georgetown CSET — Center for Security and Emerging Technology. AI policy research and national security analysis.",
      focus: "AI policy / national security research", palantir_specific: false },
    { handle: "CNASdc",             tier: 2, category: "policy",         platform: "X",
      description: "CNAS — Center for a New American Security. Defense policy research, military AI, and strategic competition.",
      focus: "Defense policy think tank", palantir_specific: false },
    { handle: "paul_scharre",       tier: 2, category: "policy",         platform: "X",
      description: "Paul Scharre — Author of 'Army of None' and 'Four Battlegrounds', VP at CNAS. Autonomous weapons and AI in warfare.",
      focus: "Military AI / autonomous systems", palantir_specific: false },
    { handle: "DefenceHQ",          tier: 1, category: "official",       platform: "X",
      description: "UK Ministry of Defence official account. UK defense program announcements, exercises, and procurement notices.",
      focus: "UK defense / MoD official", palantir_specific: false },
  ],

  rss_feeds: [
    // === PALANTIR-SPECIFIC SUBSTACKS ===
    { name: "Shyam Sankar",       url: "https://shyamsankar.com/feed",                    category: "leadership",    platform: "Blog",
      filter_palantir: false, palantir_specific: true,
      description: "Palantir CTO's personal blog. Essays on software, AI, national security, and building enduring institutions. Every post is relevant.",
      frequency: "Monthly" },
    { name: "Amit Kukreja",       url: "https://amitsdeepdives.substack.com/feed",         category: "analyst",       platform: "Substack",
      filter_palantir: false, palantir_specific: true,
      description: "Palantir-dedicated investment newsletter. Deep dives on quarterly earnings, contract analysis, and long-term thesis. Very high signal.",
      frequency: "Weekly" },
    { name: "Arny Trezzi",        url: "https://arnytrezzi.substack.com/feed",             category: "analyst",       platform: "Substack",
      filter_palantir: false, palantir_specific: true,
      description: "European Palantir investor newsletter. Contract updates, competitive analysis, and investor-oriented commentary.",
      frequency: "Weekly" },
    { name: "First Breakfast",    url: "https://firstbreakfast.substack.com/feed",         category: "analyst",       platform: "Substack",
      filter_palantir: false, palantir_specific: true,
      description: "Palantir-focused publication written by active Palantir staff — Shyam Sankar, Madeline Hart, Greg Little, Blake Seitz. >7,000 subscribers. Primary source.",
      frequency: "Weekly", note: "Written by Palantir staff — highest-fidelity insider perspective available publicly" },

    // === OFFICIAL PALANTIR BLOGS ===
    { name: "Palantir (Medium)",    url: "https://medium.com/feed/palantir",                category: "official",      platform: "Medium",
      filter_palantir: false, palantir_specific: true,
      description: "Official Palantir blog. Case studies, product announcements, partnership stories, and company perspectives.",
      frequency: "Monthly" },

    // === DEFENSE TECH PODCASTS & NEWSLETTERS ===
    { name: "Crossing the Valley",  url: "https://frontdoordefense.substack.com/feed",     category: "defense_media", platform: "Substack / Podcast",
      filter_palantir: true, palantir_specific: false,
      description: "Noah Sheinbaum's 'Crossing the Valley' podcast and newsletter. Interviews with founders, operators, and investors building defense tech. Palantir often featured.",
      frequency: "Weekly", note: "Also available on Spotify and YouTube" },

    // === DEFENSE MEDIA (FILTERED FOR PALANTIR MENTIONS) ===
    { name: "Breaking Defense",     url: "https://breakingdefense.com/feed/",               category: "defense_media", platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "Breaking Defense — the most widely read defense industry publication. Contract awards, program news, and policy analysis. Only Palantir-mentioning articles are ingested.",
      frequency: "Daily (filtered)" },
    { name: "Defense One",          url: "https://www.defenseone.com/rss/all/",             category: "defense_media", platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "Defense One — national security and defense technology news from Government Executive Media. Covers Pentagon, IC, and emerging tech.",
      frequency: "Daily (filtered)" },
    { name: "C4ISRNET",             url: "https://www.c4isrnet.com/arc/outboundfeeds/rss/", category: "defense_media", platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "C4ISRNET — specialist coverage of command & control, communications, ISR systems, and battlefield tech. Key source for Maven/TITAN coverage.",
      frequency: "Daily (filtered)" },
    { name: "FedScoop",             url: "https://fedscoop.com/feed/",                      category: "media",         platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "FedScoop — federal IT and digital government news. Covers civilian agency tech buys, cloud contracts, and AI adoption across government.",
      frequency: "Daily (filtered)" },
    { name: "War on the Rocks",     url: "https://warontherocks.com/feed/",                 category: "defense_media", platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "War on the Rocks — practitioner-driven national security analysis. Long-form essays by former military, intelligence, and policy officials.",
      frequency: "Daily (filtered)" },
    { name: "Lawfare",              url: "https://lawfaremedia.org/feed/",                  category: "media",         platform: "RSS",
      filter_palantir: true, palantir_specific: false,
      description: "Lawfare — national security law, policy, and intelligence. Tracks surveillance, AI governance, export controls, and government contracting legality.",
      frequency: "Daily (filtered)" },
    { name: "Import AI",            url: "https://importai.substack.com/feed",              category: "media",         platform: "Substack",
      filter_palantir: true, palantir_specific: false,
      description: "Jack Clark's (Anthropic co-founder) AI newsletter. Tracks defense AI, capability research, and government adoption of AI systems.",
      frequency: "Weekly (filtered)" },
    { name: "Big Technology",       url: "https://bigtechnology.substack.com/feed",         category: "media",         platform: "Substack",
      filter_palantir: true, palantir_specific: false,
      description: "Alex Kantrowitz — Big Tech accountability journalism. Covers AI policy, government contracts, and Silicon Valley's defense industry turn.",
      frequency: "Weekly (filtered)" },
    { name: "Nonzero Newsletter",   url: "https://nonzero.substack.com/feed",               category: "media",         platform: "Substack",
      filter_palantir: true, palantir_specific: false,
      description: "Robert Wright's foreign policy and AI newsletter. Strategic competition, AI arms race, and technology's role in geopolitics.",
      frequency: "Weekly (filtered)" },
  ],

  contract_apis: [
    { name: "USASpending.gov",      module: "us_spending",      country: "United States",
      description: "Official US federal awards database managed by Treasury. All Palantir contract awards, task orders, and modifications across every federal agency. Full history 2008–present.",
      url: "https://api.usaspending.gov", data_type: "Contract Awards", free: true, auth_required: false },
    { name: "UK Contracts Finder",  module: "uk_contracts",     country: "United Kingdom",
      description: "UK Government's official contract opportunity and award database. Covers all UK central government and Crown Commercial Service contracts.",
      url: "https://www.contractsfinder.service.gov.uk", data_type: "Contract Awards", free: true, auth_required: false },
    { name: "EU TED",               module: "eu_ted",           country: "EU / NATO",
      description: "Tenders Electronic Daily — official EU procurement journal. All contract awards across EU member states and NATO partner nations above threshold values.",
      url: "https://ted.europa.eu", data_type: "Contract Awards", free: true, auth_required: false },
    { name: "CanadaBuys",           module: "canada",           country: "Canada",
      description: "Government of Canada's official procurement portal and Open Canada data. Federal contracts and standing offers across all departments.",
      url: "https://canadabuys.canada.ca", data_type: "Contract Awards", free: true, auth_required: false },
    { name: "AusTender",            module: "australia",        country: "Australia",
      description: "Australian Government's AusTender procurement platform. All Commonwealth contract notices and award data.",
      url: "https://www.austender.gov.au", data_type: "Contract Awards", free: true, auth_required: false },
    { name: "Prozorro",             module: "ukraine_prozorro", country: "Ukraine",
      description: "Ukraine's open government procurement platform. All Ukrainian public contracts — critical for tracking wartime Palantir support contracts.",
      url: "https://prozorro.gov.ua", data_type: "Contract Awards", free: true, auth_required: false },
  ],

  podcasts: [
    { name: "Palantir Tech (Official)", channel: "palantirtech",   platform: "YouTube", category: "official",
      filter_palantir: false, palantir_specific: true,
      description: "Palantir's official YouTube channel. Product demos, platform walkthroughs, AIPCon sessions, live events, executive interviews, and customer stories.",
      frequency: "Ongoing" },
    { name: "Code and Connor",      channel: "codestrap8031",      platform: "YouTube", category: "analyst",
      filter_palantir: false, palantir_specific: true,
      description: "Codestrap — Connor's Palantir-focused YouTube channel. Contract breakdowns, product analysis, earnings reactions, and long-form investor commentary.",
      frequency: "Weekly" },
    { name: "American Optimist",    channel: "Joe_Lonsdale",       platform: "YouTube", category: "leadership",
      filter_palantir: true, palantir_specific: false,
      description: "Joe Lonsdale's podcast — Palantir co-founder interviews founders, investors, and policy leaders on tech, defense, and building America. Palantir-mentioning episodes only.",
      frequency: "Weekly" },
    { name: "Palantir Bullets",     channel: "ArnyTrezzi",         platform: "YouTube", category: "analyst",
      filter_palantir: false, palantir_specific: true,
      description: "Arny Trezzi's YouTube channel — concise Palantir news breakdowns, contract analysis, and investor-oriented video commentary.",
      frequency: "Weekly" },
    { name: "Palantir Weekly",      channel: "AmitKukreja",        platform: "YouTube", category: "analyst",
      filter_palantir: false, palantir_specific: true,
      description: "Amit Kukreja's YouTube channel — Palantir weekly and daily video updates, earnings recaps, and deep dives on contracts and thesis.",
      frequency: "Daily / Weekly" },
    { name: "Odd Lots",             url: "https://youtube.com/playlist?list=PLe4PRejZgr0MuA6M0zkZyy-99-qc87wKV", platform: "YouTube", category: "media",
      filter_palantir: true, palantir_specific: false,
      description: "Bloomberg's Odd Lots podcast by Tracy Alloway and Joe Weisenthal — macroeconomics, markets, and tech. Palantir-mentioning episodes only.",
      frequency: "Daily (filtered)" },
  ],

  disclosure_sources: [
    { name: "SEC EDGAR (8-K)",      module: "sec_edgar",    cik: "0001321655",
      description: "Palantir's SEC filings via EDGAR. 8-K material event disclosures include contract announcements, financial results, and significant agreements filed with the SEC within 4 business days.",
      url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001321655&type=8-K", data_type: "Regulatory Filing", free: true, auth_required: false },
    { name: "Palantir IR",          module: "palantir_ir",
      description: "Palantir Investor Relations press releases at investors.palantir.com. Contract announcements, partnership news, and financial guidance — all official and pre-SEC-filed.",
      url: "https://investors.palantir.com/news-releases", data_type: "Press Release", free: true, auth_required: false },
  ],
};
